use Grab
go


-- DATA for districts
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('760',N'1',N'1',N'Quận 1',N'District 1',N'1',N'79',5),
	 ('761',N'12',N'12',N'Quận 12',N'District 12',N'12',N'79',5),
	 ('770',N'3',N'3',N'Quận 3',N'District 3',N'3',N'79',5),
	 ('771',N'10',N'10',N'Quận 10',N'District 10',N'10',N'79',5),
	 ('772',N'11',N'11',N'Quận 11',N'District 11',N'11',N'79',5),
	 ('773',N'4',N'4',N'Quận 4',N'District 4',N'4',N'79',5),
	 ('774',N'5',N'5',N'Quận 5',N'District 5',N'5',N'79',5),
	 ('775',N'6',N'6',N'Quận 6',N'District 6',N'6',N'79',5),
	 ('776',N'8',N'8',N'Quận 8',N'District 8',N'8',N'79',5),
	 ('778',N'7',N'7',N'Quận 7',N'District 7',N'7',N'79',5);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('725',N'Thuận An',N'Thuan An',N'Thành phố Thuận An',N'Thuan An City',N'thuan an',N'74',4),
	 ('001',N'Ba Đình',N'Ba Dinh',N'Quận Ba Đình',N'Ba Dinh District',N'ba dinh',N'01',5),
	 ('002',N'Hoàn Kiếm',N'Hoan Kiem',N'Quận Hoàn Kiếm',N'Hoan Kiem District',N'hoan kiem',N'01',5),
	 ('003',N'Tây Hồ',N'Tay Ho',N'Quận Tây Hồ',N'Tay Ho District',N'tay ho',N'01',5),
	 ('004',N'Long Biên',N'Long Bien',N'Quận Long Biên',N'Long Bien District',N'long bien',N'01',5),
	 ('005',N'Cầu Giấy',N'Cau Giay',N'Quận Cầu Giấy',N'Cau Giay District',N'cau giay',N'01',5),
	 ('006',N'Đống Đa',N'Dong Da',N'Quận Đống Đa',N'Dong Da District',N'dong da',N'01',5),
	 ('007',N'Hai Bà Trưng',N'Hai Ba Trung',N'Quận Hai Bà Trưng',N'Hai Ba Trung District',N'hai ba trung',N'01',5),
	 ('008',N'Hoàng Mai',N'Hoang Mai',N'Quận Hoàng Mai',N'Hoang Mai District',N'hoang mai',N'01',5),
	 ('009',N'Thanh Xuân',N'Thanh Xuan',N'Quận Thanh Xuân',N'Thanh Xuan District',N'thanh xuan',N'01',5);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('016',N'Sóc Sơn',N'Soc Son',N'Huyện Sóc Sơn',N'Soc Son District',N'soc son',N'01',7),
	 ('017',N'Đông Anh',N'Dong Anh',N'Huyện Đông Anh',N'Dong Anh District',N'dong anh',N'01',7),
	 ('018',N'Gia Lâm',N'Gia Lam',N'Huyện Gia Lâm',N'Gia Lam District',N'gia lam',N'01',7),
	 ('019',N'Nam Từ Liêm',N'Nam Tu Liem',N'Quận Nam Từ Liêm',N'Nam Tu Liem District',N'nam tu liem',N'01',5),
	 ('020',N'Thanh Trì',N'Thanh Tri',N'Huyện Thanh Trì',N'Thanh Tri District',N'thanh tri',N'01',7),
	 ('021',N'Bắc Từ Liêm',N'Bac Tu Liem',N'Quận Bắc Từ Liêm',N'Bac Tu Liem District',N'bac tu liem',N'01',5),
	 ('250',N'Mê Linh',N'Me Linh',N'Huyện Mê Linh',N'Me Linh District',N'me linh',N'01',7),
	 ('268',N'Hà Đông',N'Ha Dong',N'Quận Hà Đông',N'Ha Dong District',N'ha dong',N'01',5),
	 ('269',N'Sơn Tây',N'Son Tay',N'Thị xã Sơn Tây',N'Son Tay Town',N'son tay',N'01',6),
	 ('271',N'Ba Vì',N'Ba Vi',N'Huyện Ba Vì',N'Ba Vi District',N'ba vi',N'01',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('272',N'Phúc Thọ',N'Phuc Tho',N'Huyện Phúc Thọ',N'Phuc Tho District',N'phuc tho',N'01',7),
	 ('273',N'Đan Phượng',N'Dan Phuong',N'Huyện Đan Phượng',N'Dan Phuong District',N'dan phuong',N'01',7),
	 ('274',N'Hoài Đức',N'Hoai Duc',N'Huyện Hoài Đức',N'Hoai Duc District',N'hoai duc',N'01',7),
	 ('275',N'Quốc Oai',N'Quoc Oai',N'Huyện Quốc Oai',N'Quoc Oai District',N'quoc oai',N'01',7),
	 ('276',N'Thạch Thất',N'Thach That',N'Huyện Thạch Thất',N'Thach That District',N'thach that',N'01',7),
	 ('277',N'Chương Mỹ',N'Chuong My',N'Huyện Chương Mỹ',N'Chuong My District',N'chuong my',N'01',7),
	 ('278',N'Thanh Oai',N'Thanh Oai',N'Huyện Thanh Oai',N'Thanh Oai District',N'thanh oai',N'01',7),
	 ('279',N'Thường Tín',N'Thuong Tin',N'Huyện Thường Tín',N'Thuong Tin District',N'thuong tin',N'01',7),
	 ('280',N'Phú Xuyên',N'Phu Xuyen',N'Huyện Phú Xuyên',N'Phu Xuyen District',N'phu xuyen',N'01',7),
	 ('281',N'Ứng Hòa',N'Ung Hoa',N'Huyện Ứng Hòa',N'Ung Hoa District',N'ung hoa',N'01',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('282',N'Mỹ Đức',N'My Duc',N'Huyện Mỹ Đức',N'My Duc District',N'my duc',N'01',7),
	 ('024',N'Hà Giang',N'Ha Giang',N'Thành phố Hà Giang',N'Ha Giang City',N'ha giang',N'02',4),
	 ('026',N'Đồng Văn',N'Dong Van',N'Huyện Đồng Văn',N'Dong Van District',N'dong van',N'02',7),
	 ('027',N'Mèo Vạc',N'Meo Vac',N'Huyện Mèo Vạc',N'Meo Vac District',N'meo vac',N'02',7),
	 ('028',N'Yên Minh',N'Yen Minh',N'Huyện Yên Minh',N'Yen Minh District',N'yen minh',N'02',7),
	 ('029',N'Quản Bạ',N'Quan Ba',N'Huyện Quản Bạ',N'Quan Ba District',N'quan ba',N'02',7),
	 ('030',N'Vị Xuyên',N'Vi Xuyen',N'Huyện Vị Xuyên',N'Vi Xuyen District',N'vi xuyen',N'02',7),
	 ('031',N'Bắc Mê',N'Bac Me',N'Huyện Bắc Mê',N'Bac Me District',N'bac me',N'02',7),
	 ('032',N'Hoàng Su Phì',N'Hoang Su Phi',N'Huyện Hoàng Su Phì',N'Hoang Su Phi District',N'hoang su phi',N'02',7),
	 ('033',N'Xín Mần',N'Xin Man',N'Huyện Xín Mần',N'Xin Man District',N'xin man',N'02',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('034',N'Bắc Quang',N'Bac Quang',N'Huyện Bắc Quang',N'Bac Quang District',N'bac quang',N'02',7),
	 ('035',N'Quang Bình',N'Quang Binh',N'Huyện Quang Bình',N'Quang Binh District',N'quang binh',N'02',7),
	 ('040',N'Cao Bằng',N'Cao Bang',N'Thành phố Cao Bằng',N'Cao Bang City',N'cao bang',N'04',4),
	 ('042',N'Bảo Lâm',N'Bao Lam',N'Huyện Bảo Lâm',N'Bao Lam District',N'bao lam',N'04',7),
	 ('043',N'Bảo Lạc',N'Bao Lac',N'Huyện Bảo Lạc',N'Bao Lac District',N'bao lac',N'04',7),
	 ('045',N'Hà Quảng',N'Ha Quang',N'Huyện Hà Quảng',N'Ha Quang District',N'ha quang',N'04',7),
	 ('047',N'Trùng Khánh',N'Trung Khanh',N'Huyện Trùng Khánh',N'Trung Khanh District',N'trung khanh',N'04',7),
	 ('048',N'Hạ Lang',N'Ha Lang',N'Huyện Hạ Lang',N'Ha Lang District',N'ha lang',N'04',7),
	 ('049',N'Quảng Hòa',N'Quang Hoa',N'Huyện Quảng Hòa',N'Quang Hoa District',N'quang hoa',N'04',7),
	 ('051',N'Hoà An',N'Hoa An',N'Huyện Hoà An',N'Hoa An District',N'hoa an',N'04',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('052',N'Nguyên Bình',N'Nguyen Binh',N'Huyện Nguyên Bình',N'Nguyen Binh District',N'nguyen binh',N'04',7),
	 ('053',N'Thạch An',N'Thach An',N'Huyện Thạch An',N'Thach An District',N'thach an',N'04',7),
	 ('058',N'Bắc Kạn',N'Bac Kan',N'Thành phố Bắc Kạn',N'Bac Kan City',N'bac kan',N'06',4),
	 ('060',N'Pác Nặm',N'Pac Nam',N'Huyện Pác Nặm',N'Pac Nam District',N'pac nam',N'06',7),
	 ('061',N'Ba Bể',N'Ba Be',N'Huyện Ba Bể',N'Ba Be District',N'ba be',N'06',7),
	 ('062',N'Ngân Sơn',N'Ngan Son',N'Huyện Ngân Sơn',N'Ngan Son District',N'ngan son',N'06',7),
	 ('063',N'Bạch Thông',N'Bach Thong',N'Huyện Bạch Thông',N'Bach Thong District',N'bach thong',N'06',7),
	 ('064',N'Chợ Đồn',N'Cho Don',N'Huyện Chợ Đồn',N'Cho Don District',N'cho don',N'06',7),
	 ('065',N'Chợ Mới',N'Cho Moi',N'Huyện Chợ Mới',N'Cho Moi District',N'cho moi',N'06',7),
	 ('066',N'Na Rì',N'Na Ri',N'Huyện Na Rì',N'Na Ri District',N'na ri',N'06',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('070',N'Tuyên Quang',N'Tuyen Quang',N'Thành phố Tuyên Quang',N'Tuyen Quang City',N'tuyen quang',N'08',4),
	 ('071',N'Lâm Bình',N'Lam Binh',N'Huyện Lâm Bình',N'Lam Binh District',N'lam binh',N'08',7),
	 ('072',N'Na Hang',N'Na Hang',N'Huyện Na Hang',N'Na Hang District',N'na hang',N'08',7),
	 ('073',N'Chiêm Hóa',N'Chiem Hoa',N'Huyện Chiêm Hóa',N'Chiem Hoa District',N'chiem hoa',N'08',7),
	 ('074',N'Hàm Yên',N'Ham Yen',N'Huyện Hàm Yên',N'Ham Yen District',N'ham yen',N'08',7),
	 ('075',N'Yên Sơn',N'Yen Son',N'Huyện Yên Sơn',N'Yen Son District',N'yen son',N'08',7),
	 ('076',N'Sơn Dương',N'Son Duong',N'Huyện Sơn Dương',N'Son Duong District',N'son duong',N'08',7),
	 ('080',N'Lào Cai',N'Lao Cai',N'Thành phố Lào Cai',N'Lao Cai City',N'lao cai',N'10',4),
	 ('082',N'Bát Xát',N'Bat Xat',N'Huyện Bát Xát',N'Bat Xat District',N'bat xat',N'10',7),
	 ('083',N'Mường Khương',N'Muong Khuong',N'Huyện Mường Khương',N'Muong Khuong District',N'muong khuong',N'10',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('084',N'Si Ma Cai',N'Si Ma Cai',N'Huyện Si Ma Cai',N'Si Ma Cai District',N'si ma cai',N'10',7),
	 ('085',N'Bắc Hà',N'Bac Ha',N'Huyện Bắc Hà',N'Bac Ha District',N'bac ha',N'10',7),
	 ('086',N'Bảo Thắng',N'Bao Thang',N'Huyện Bảo Thắng',N'Bao Thang District',N'bao thang',N'10',7),
	 ('087',N'Bảo Yên',N'Bao Yen',N'Huyện Bảo Yên',N'Bao Yen District',N'bao yen',N'10',7),
	 ('088',N'Sa Pa',N'Sa Pa',N'Thị xã Sa Pa',N'Sa Pa Town',N'sa pa',N'10',6),
	 ('089',N'Văn Bàn',N'Van Ban',N'Huyện Văn Bàn',N'Van Ban District',N'van ban',N'10',7),
	 ('094',N'Điện Biên Phủ',N'Dien Bien Phu',N'Thành phố Điện Biên Phủ',N'Dien Bien Phu City',N'dien bien phu',N'11',4),
	 ('095',N'Mường Lay',N'Muong Lay',N'Thị xã Mường Lay',N'Muong Lay Town',N'muong lay',N'11',6),
	 ('096',N'Mường Nhé',N'Muong Nhe',N'Huyện Mường Nhé',N'Muong Nhe District',N'muong nhe',N'11',7),
	 ('097',N'Mường Chà',N'Muong Cha',N'Huyện Mường Chà',N'Muong Cha District',N'muong cha',N'11',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('098',N'Tủa Chùa',N'Tua Chua',N'Huyện Tủa Chùa',N'Tua Chua District',N'tua chua',N'11',7),
	 ('099',N'Tuần Giáo',N'Tuan Giao',N'Huyện Tuần Giáo',N'Tuan Giao District',N'tuan giao',N'11',7),
	 ('100',N'Điện Biên',N'Dien Bien',N'Huyện Điện Biên',N'Dien Bien District',N'dien bien',N'11',7),
	 ('101',N'Điện Biên Đông',N'Dien Bien Dong',N'Huyện Điện Biên Đông',N'Dien Bien Dong District',N'dien bien dong',N'11',7),
	 ('102',N'Mường Ảng',N'Muong Ang',N'Huyện Mường Ảng',N'Muong Ang District',N'muong ang',N'11',7),
	 ('103',N'Nậm Pồ',N'Nam Po',N'Huyện Nậm Pồ',N'Nam Po District',N'nam po',N'11',7),
	 ('105',N'Lai Châu',N'Lai Chau',N'Thành phố Lai Châu',N'Lai Chau City',N'lai chau',N'12',4),
	 ('106',N'Tam Đường',N'Tam Duong',N'Huyện Tam Đường',N'Tam Duong District',N'tam duong',N'12',7),
	 ('107',N'Mường Tè',N'Muong Te',N'Huyện Mường Tè',N'Muong Te District',N'muong te',N'12',7),
	 ('108',N'Sìn Hồ',N'Sin Ho',N'Huyện Sìn Hồ',N'Sin Ho District',N'sin ho',N'12',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('109',N'Phong Thổ',N'Phong Tho',N'Huyện Phong Thổ',N'Phong Tho District',N'phong tho',N'12',7),
	 ('110',N'Than Uyên',N'Than Uyen',N'Huyện Than Uyên',N'Than Uyen District',N'than uyen',N'12',7),
	 ('111',N'Tân Uyên',N'Tan Uyen',N'Huyện Tân Uyên',N'Tan Uyen District',N'tan uyen',N'12',7),
	 ('112',N'Nậm Nhùn',N'Nam Nhun',N'Huyện Nậm Nhùn',N'Nam Nhun District',N'nam nhun',N'12',7),
	 ('116',N'Sơn La',N'Son La',N'Thành phố Sơn La',N'Son La City',N'son la',N'14',4),
	 ('118',N'Quỳnh Nhai',N'Quynh Nhai',N'Huyện Quỳnh Nhai',N'Quynh Nhai District',N'quynh nhai',N'14',7),
	 ('119',N'Thuận Châu',N'Thuan Chau',N'Huyện Thuận Châu',N'Thuan Chau District',N'thuan chau',N'14',7),
	 ('120',N'Mường La',N'Muong La',N'Huyện Mường La',N'Muong La District',N'muong la',N'14',7),
	 ('121',N'Bắc Yên',N'Bac Yen',N'Huyện Bắc Yên',N'Bac Yen District',N'bac yen',N'14',7),
	 ('122',N'Phù Yên',N'Phu Yen',N'Huyện Phù Yên',N'Phu Yen District',N'phu yen',N'14',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('123',N'Mộc Châu',N'Moc Chau',N'Huyện Mộc Châu',N'Moc Chau District',N'moc chau',N'14',7),
	 ('124',N'Yên Châu',N'Yen Chau',N'Huyện Yên Châu',N'Yen Chau District',N'yen chau',N'14',7),
	 ('125',N'Mai Sơn',N'Mai Son',N'Huyện Mai Sơn',N'Mai Son District',N'mai son',N'14',7),
	 ('126',N'Sông Mã',N'Song Ma',N'Huyện Sông Mã',N'Song Ma District',N'song ma',N'14',7),
	 ('127',N'Sốp Cộp',N'Sop Cop',N'Huyện Sốp Cộp',N'Sop Cop District',N'sop cop',N'14',7),
	 ('128',N'Vân Hồ',N'Van Ho',N'Huyện Vân Hồ',N'Van Ho District',N'van ho',N'14',7),
	 ('132',N'Yên Bái',N'Yen Bai',N'Thành phố Yên Bái',N'Yen Bai City',N'yen bai',N'15',4),
	 ('133',N'Nghĩa Lộ',N'Nghia Lo',N'Thị xã Nghĩa Lộ',N'Nghia Lo Town',N'nghia lo',N'15',6),
	 ('135',N'Lục Yên',N'Luc Yen',N'Huyện Lục Yên',N'Luc Yen District',N'luc yen',N'15',7),
	 ('136',N'Văn Yên',N'Van Yen',N'Huyện Văn Yên',N'Van Yen District',N'van yen',N'15',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('137',N'Mù Căng Chải',N'Mu Cang Chai',N'Huyện Mù Căng Chải',N'Mu Cang Chai District',N'mu cang chai',N'15',7),
	 ('138',N'Trấn Yên',N'Tran Yen',N'Huyện Trấn Yên',N'Tran Yen District',N'tran yen',N'15',7),
	 ('139',N'Trạm Tấu',N'Tram Tau',N'Huyện Trạm Tấu',N'Tram Tau District',N'tram tau',N'15',7),
	 ('140',N'Văn Chấn',N'Van Chan',N'Huyện Văn Chấn',N'Van Chan District',N'van chan',N'15',7),
	 ('141',N'Yên Bình',N'Yen Binh',N'Huyện Yên Bình',N'Yen Binh District',N'yen binh',N'15',7),
	 ('148',N'Hòa Bình',N'Hoa Binh',N'Thành phố Hòa Bình',N'Hoa Binh City',N'hoa binh',N'17',4),
	 ('150',N'Đà Bắc',N'Da Bac',N'Huyện Đà Bắc',N'Da Bac District',N'da bac',N'17',7),
	 ('152',N'Lương Sơn',N'Luong Son',N'Huyện Lương Sơn',N'Luong Son District',N'luong son',N'17',7),
	 ('153',N'Kim Bôi',N'Kim Boi',N'Huyện Kim Bôi',N'Kim Boi District',N'kim boi',N'17',7),
	 ('154',N'Cao Phong',N'Cao Phong',N'Huyện Cao Phong',N'Cao Phong District',N'cao phong',N'17',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('155',N'Tân Lạc',N'Tan Lac',N'Huyện Tân Lạc',N'Tan Lac District',N'tan lac',N'17',7),
	 ('156',N'Mai Châu',N'Mai Chau',N'Huyện Mai Châu',N'Mai Chau District',N'mai chau',N'17',7),
	 ('157',N'Lạc Sơn',N'Lac Son',N'Huyện Lạc Sơn',N'Lac Son District',N'lac son',N'17',7),
	 ('158',N'Yên Thủy',N'Yen Thuy',N'Huyện Yên Thủy',N'Yen Thuy District',N'yen thuy',N'17',7),
	 ('159',N'Lạc Thủy',N'Lac Thuy',N'Huyện Lạc Thủy',N'Lac Thuy District',N'lac thuy',N'17',7),
	 ('164',N'Thái Nguyên',N'Thai Nguyen',N'Thành phố Thái Nguyên',N'Thai Nguyen City',N'thai nguyen',N'19',4),
	 ('165',N'Sông Công',N'Song Cong',N'Thành phố Sông Công',N'Song Cong City',N'song cong',N'19',4),
	 ('167',N'Định Hóa',N'Dinh Hoa',N'Huyện Định Hóa',N'Dinh Hoa District',N'dinh hoa',N'19',7),
	 ('168',N'Phú Lương',N'Phu Luong',N'Huyện Phú Lương',N'Phu Luong District',N'phu luong',N'19',7),
	 ('169',N'Đồng Hỷ',N'Dong Hy',N'Huyện Đồng Hỷ',N'Dong Hy District',N'dong hy',N'19',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('170',N'Võ Nhai',N'Vo Nhai',N'Huyện Võ Nhai',N'Vo Nhai District',N'vo nhai',N'19',7),
	 ('171',N'Đại Từ',N'Dai Tu',N'Huyện Đại Từ',N'Dai Tu District',N'dai tu',N'19',7),
	 ('172',N'Phổ Yên',N'Pho Yen',N'Thành phố Phổ Yên',N'Pho Yen City',N'pho yen',N'19',4),
	 ('173',N'Phú Bình',N'Phu Binh',N'Huyện Phú Bình',N'Phu Binh District',N'phu binh',N'19',7),
	 ('178',N'Lạng Sơn',N'Lang Son',N'Thành phố Lạng Sơn',N'Lang Son City',N'lang son',N'20',4),
	 ('180',N'Tràng Định',N'Trang Dinh',N'Huyện Tràng Định',N'Trang Dinh District',N'trang dinh',N'20',7),
	 ('181',N'Bình Gia',N'Binh Gia',N'Huyện Bình Gia',N'Binh Gia District',N'binh gia',N'20',7),
	 ('182',N'Văn Lãng',N'Van Lang',N'Huyện Văn Lãng',N'Van Lang District',N'van lang',N'20',7),
	 ('183',N'Cao Lộc',N'Cao Loc',N'Huyện Cao Lộc',N'Cao Loc District',N'cao loc',N'20',7),
	 ('184',N'Văn Quan',N'Van Quan',N'Huyện Văn Quan',N'Van Quan District',N'van quan',N'20',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('185',N'Bắc Sơn',N'Bac Son',N'Huyện Bắc Sơn',N'Bac Son District',N'bac son',N'20',7),
	 ('186',N'Hữu Lũng',N'Huu Lung',N'Huyện Hữu Lũng',N'Huu Lung District',N'huu lung',N'20',7),
	 ('187',N'Chi Lăng',N'Chi Lang',N'Huyện Chi Lăng',N'Chi Lang District',N'chi lang',N'20',7),
	 ('188',N'Lộc Bình',N'Loc Binh',N'Huyện Lộc Bình',N'Loc Binh District',N'loc binh',N'20',7),
	 ('189',N'Đình Lập',N'Dinh Lap',N'Huyện Đình Lập',N'Dinh Lap District',N'dinh lap',N'20',7),
	 ('193',N'Hạ Long',N'Ha Long',N'Thành phố Hạ Long',N'Ha Long City',N'ha long',N'22',4),
	 ('194',N'Móng Cái',N'Mong Cai',N'Thành phố Móng Cái',N'Mong Cai City',N'mong cai',N'22',4),
	 ('195',N'Cẩm Phả',N'Cam Pha',N'Thành phố Cẩm Phả',N'Cam Pha City',N'cam pha',N'22',4),
	 ('196',N'Uông Bí',N'Uong Bi',N'Thành phố Uông Bí',N'Uong Bi City',N'uong bi',N'22',4),
	 ('198',N'Bình Liêu',N'Binh Lieu',N'Huyện Bình Liêu',N'Binh Lieu District',N'binh lieu',N'22',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('199',N'Tiên Yên',N'Tien Yen',N'Huyện Tiên Yên',N'Tien Yen District',N'tien yen',N'22',7),
	 ('200',N'Đầm Hà',N'Dam Ha',N'Huyện Đầm Hà',N'Dam Ha District',N'dam ha',N'22',7),
	 ('201',N'Hải Hà',N'Hai Ha',N'Huyện Hải Hà',N'Hai Ha District',N'hai ha',N'22',7),
	 ('202',N'Ba Chẽ',N'Ba Che',N'Huyện Ba Chẽ',N'Ba Che District',N'ba che',N'22',7),
	 ('203',N'Vân Đồn',N'Van Don',N'Huyện Vân Đồn',N'Van Don District',N'van don',N'22',7),
	 ('205',N'Đông Triều',N'Dong Trieu',N'Thị xã Đông Triều',N'Dong Trieu Town',N'dong trieu',N'22',6),
	 ('206',N'Quảng Yên',N'Quang Yen',N'Thị xã Quảng Yên',N'Quang Yen Town',N'quang yen',N'22',6),
	 ('207',N'Cô Tô',N'Co To',N'Huyện Cô Tô',N'Co To District',N'co to',N'22',7),
	 ('213',N'Bắc Giang',N'Bac Giang',N'Thành phố Bắc Giang',N'Bac Giang City',N'bac giang',N'24',4),
	 ('215',N'Yên Thế',N'Yen The',N'Huyện Yên Thế',N'Yen The District',N'yen the',N'24',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('216',N'Tân Yên',N'Tan Yen',N'Huyện Tân Yên',N'Tan Yen District',N'tan yen',N'24',7),
	 ('217',N'Lạng Giang',N'Lang Giang',N'Huyện Lạng Giang',N'Lang Giang District',N'lang giang',N'24',7),
	 ('218',N'Lục Nam',N'Luc Nam',N'Huyện Lục Nam',N'Luc Nam District',N'luc nam',N'24',7),
	 ('219',N'Lục Ngạn',N'Luc Ngan',N'Huyện Lục Ngạn',N'Luc Ngan District',N'luc ngan',N'24',7),
	 ('220',N'Sơn Động',N'Son Dong',N'Huyện Sơn Động',N'Son Dong District',N'son dong',N'24',7),
	 ('221',N'Yên Dũng',N'Yen Dung',N'Huyện Yên Dũng',N'Yen Dung District',N'yen dung',N'24',7),
	 ('222',N'Việt Yên',N'Viet Yen',N'Huyện Việt Yên',N'Viet Yen District',N'viet yen',N'24',7),
	 ('223',N'Hiệp Hòa',N'Hiep Hoa',N'Huyện Hiệp Hòa',N'Hiep Hoa District',N'hiep hoa',N'24',7),
	 ('227',N'Việt Trì',N'Viet Tri',N'Thành phố Việt Trì',N'Viet Tri City',N'viet tri',N'25',4),
	 ('228',N'Phú Thọ',N'Phu Tho',N'Thị xã Phú Thọ',N'Phu Tho Town',N'phu tho',N'25',6);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('230',N'Đoan Hùng',N'Doan Hung',N'Huyện Đoan Hùng',N'Doan Hung District',N'doan hung',N'25',7),
	 ('231',N'Hạ Hoà',N'Ha Hoa',N'Huyện Hạ Hoà',N'Ha Hoa District',N'ha hoa',N'25',7),
	 ('232',N'Thanh Ba',N'Thanh Ba',N'Huyện Thanh Ba',N'Thanh Ba District',N'thanh ba',N'25',7),
	 ('233',N'Phù Ninh',N'Phu Ninh',N'Huyện Phù Ninh',N'Phu Ninh District',N'phu ninh',N'25',7),
	 ('234',N'Yên Lập',N'Yen Lap',N'Huyện Yên Lập',N'Yen Lap District',N'yen lap',N'25',7),
	 ('235',N'Cẩm Khê',N'Cam Khe',N'Huyện Cẩm Khê',N'Cam Khe District',N'cam khe',N'25',7),
	 ('236',N'Tam Nông',N'Tam Nong',N'Huyện Tam Nông',N'Tam Nong District',N'tam nong',N'25',7),
	 ('237',N'Lâm Thao',N'Lam Thao',N'Huyện Lâm Thao',N'Lam Thao District',N'lam thao',N'25',7),
	 ('238',N'Thanh Sơn',N'Thanh Son',N'Huyện Thanh Sơn',N'Thanh Son District',N'thanh son',N'25',7),
	 ('239',N'Thanh Thuỷ',N'Thanh Thuy',N'Huyện Thanh Thuỷ',N'Thanh Thuy District',N'thanh thuy',N'25',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('240',N'Tân Sơn',N'Tan Son',N'Huyện Tân Sơn',N'Tan Son District',N'tan son',N'25',7),
	 ('243',N'Vĩnh Yên',N'Vinh Yen',N'Thành phố Vĩnh Yên',N'Vinh Yen City',N'vinh yen',N'26',4),
	 ('244',N'Phúc Yên',N'Phuc Yen',N'Thành phố Phúc Yên',N'Phuc Yen City',N'phuc yen',N'26',4),
	 ('246',N'Lập Thạch',N'Lap Thach',N'Huyện Lập Thạch',N'Lap Thach District',N'lap thach',N'26',7),
	 ('247',N'Tam Dương',N'Tam Duong',N'Huyện Tam Dương',N'Tam Duong District',N'tam duong',N'26',7),
	 ('248',N'Tam Đảo',N'Tam Dao',N'Huyện Tam Đảo',N'Tam Dao District',N'tam dao',N'26',7),
	 ('249',N'Bình Xuyên',N'Binh Xuyen',N'Huyện Bình Xuyên',N'Binh Xuyen District',N'binh xuyen',N'26',7),
	 ('251',N'Yên Lạc',N'Yen Lac',N'Huyện Yên Lạc',N'Yen Lac District',N'yen lac',N'26',7),
	 ('252',N'Vĩnh Tường',N'Vinh Tuong',N'Huyện Vĩnh Tường',N'Vinh Tuong District',N'vinh tuong',N'26',7),
	 ('253',N'Sông Lô',N'Song Lo',N'Huyện Sông Lô',N'Song Lo District',N'song lo',N'26',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('256',N'Bắc Ninh',N'Bac Ninh',N'Thành phố Bắc Ninh',N'Bac Ninh City',N'bac ninh',N'27',4),
	 ('258',N'Yên Phong',N'Yen Phong',N'Huyện Yên Phong',N'Yen Phong District',N'yen phong',N'27',7),
	 ('259',N'Quế Võ',N'Que Vo',N'Huyện Quế Võ',N'Que Vo District',N'que vo',N'27',7),
	 ('260',N'Tiên Du',N'Tien Du',N'Huyện Tiên Du',N'Tien Du District',N'tien du',N'27',7),
	 ('261',N'Từ Sơn',N'Tu Son',N'Thành phố Từ Sơn',N'Tu Son City',N'tu son',N'27',4),
	 ('262',N'Thuận Thành',N'Thuan Thanh',N'Huyện Thuận Thành',N'Thuan Thanh District',N'thuan thanh',N'27',7),
	 ('263',N'Gia Bình',N'Gia Binh',N'Huyện Gia Bình',N'Gia Binh District',N'gia binh',N'27',7),
	 ('264',N'Lương Tài',N'Luong Tai',N'Huyện Lương Tài',N'Luong Tai District',N'luong tai',N'27',7),
	 ('288',N'Hải Dương',N'Hai Duong',N'Thành phố Hải Dương',N'Hai Duong City',N'hai duong',N'30',4),
	 ('290',N'Chí Linh',N'Chi Linh',N'Thành phố Chí Linh',N'Chi Linh City',N'chi linh',N'30',4);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('291',N'Nam Sách',N'Nam Sach',N'Huyện Nam Sách',N'Nam Sach District',N'nam sach',N'30',7),
	 ('292',N'Kinh Môn',N'Kinh Mon',N'Thị xã Kinh Môn',N'Kinh Mon Town',N'kinh mon',N'30',6),
	 ('293',N'Kim Thành',N'Kim Thanh',N'Huyện Kim Thành',N'Kim Thanh District',N'kim thanh',N'30',7),
	 ('294',N'Thanh Hà',N'Thanh Ha',N'Huyện Thanh Hà',N'Thanh Ha District',N'thanh ha',N'30',7),
	 ('295',N'Cẩm Giàng',N'Cam Giang',N'Huyện Cẩm Giàng',N'Cam Giang District',N'cam giang',N'30',7),
	 ('296',N'Bình Giang',N'Binh Giang',N'Huyện Bình Giang',N'Binh Giang District',N'binh giang',N'30',7),
	 ('297',N'Gia Lộc',N'Gia Loc',N'Huyện Gia Lộc',N'Gia Loc District',N'gia loc',N'30',7),
	 ('298',N'Tứ Kỳ',N'Tu Ky',N'Huyện Tứ Kỳ',N'Tu Ky District',N'tu ky',N'30',7),
	 ('299',N'Ninh Giang',N'Ninh Giang',N'Huyện Ninh Giang',N'Ninh Giang District',N'ninh giang',N'30',7),
	 ('300',N'Thanh Miện',N'Thanh Mien',N'Huyện Thanh Miện',N'Thanh Mien District',N'thanh mien',N'30',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('303',N'Hồng Bàng',N'Hong Bang',N'Quận Hồng Bàng',N'Hong Bang District',N'hong bang',N'31',5),
	 ('304',N'Ngô Quyền',N'Ngo Quyen',N'Quận Ngô Quyền',N'Ngo Quyen District',N'ngo quyen',N'31',5),
	 ('305',N'Lê Chân',N'Le Chan',N'Quận Lê Chân',N'Le Chan District',N'le chan',N'31',5),
	 ('306',N'Hải An',N'Hai An',N'Quận Hải An',N'Hai An District',N'hai an',N'31',5),
	 ('307',N'Kiến An',N'Kien An',N'Quận Kiến An',N'Kien An District',N'kien an',N'31',5),
	 ('308',N'Đồ Sơn',N'Do Son',N'Quận Đồ Sơn',N'Do Son District',N'do son',N'31',5),
	 ('309',N'Dương Kinh',N'Duong Kinh',N'Quận Dương Kinh',N'Duong Kinh District',N'duong kinh',N'31',5),
	 ('311',N'Thuỷ Nguyên',N'Thuy Nguyen',N'Huyện Thuỷ Nguyên',N'Thuy Nguyen District',N'thuy nguyen',N'31',7),
	 ('312',N'An Dương',N'An Duong',N'Huyện An Dương',N'An Duong District',N'an duong',N'31',7),
	 ('313',N'An Lão',N'An Lao',N'Huyện An Lão',N'An Lao District',N'an lao',N'31',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('314',N'Kiến Thuỵ',N'Kien Thuy',N'Huyện Kiến Thuỵ',N'Kien Thuy District',N'kien thuy',N'31',7),
	 ('315',N'Tiên Lãng',N'Tien Lang',N'Huyện Tiên Lãng',N'Tien Lang District',N'tien lang',N'31',7),
	 ('710',N'Gò Dầu',N'Go Dau',N'Huyện Gò Dầu',N'Go Dau District',N'go dau',N'72',7),
	 ('316',N'Vĩnh Bảo',N'Vinh Bao',N'Huyện Vĩnh Bảo',N'Vinh Bao District',N'vinh bao',N'31',7),
	 ('317',N'Cát Hải',N'Cat Hai',N'Huyện Cát Hải',N'Cat Hai District',N'cat hai',N'31',7),
	 ('318',N'Bạch Long Vĩ',N'Bach Long Vi',N'Huyện Bạch Long Vĩ',N'Bach Long Vi District',N'bach long vi',N'31',7),
	 ('323',N'Hưng Yên',N'Hung Yen',N'Thành phố Hưng Yên',N'Hung Yen City',N'hung yen',N'33',4),
	 ('325',N'Văn Lâm',N'Van Lam',N'Huyện Văn Lâm',N'Van Lam District',N'van lam',N'33',7),
	 ('326',N'Văn Giang',N'Van Giang',N'Huyện Văn Giang',N'Van Giang District',N'van giang',N'33',7),
	 ('327',N'Yên Mỹ',N'Yen My',N'Huyện Yên Mỹ',N'Yen My District',N'yen my',N'33',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('328',N'Mỹ Hào',N'My Hao',N'Thị xã Mỹ Hào',N'My Hao Town',N'my hao',N'33',6),
	 ('329',N'Ân Thi',N'An Thi',N'Huyện Ân Thi',N'An Thi District',N'an thi',N'33',7),
	 ('330',N'Khoái Châu',N'Khoai Chau',N'Huyện Khoái Châu',N'Khoai Chau District',N'khoai chau',N'33',7),
	 ('331',N'Kim Động',N'Kim Dong',N'Huyện Kim Động',N'Kim Dong District',N'kim dong',N'33',7),
	 ('332',N'Tiên Lữ',N'Tien Lu',N'Huyện Tiên Lữ',N'Tien Lu District',N'tien lu',N'33',7),
	 ('333',N'Phù Cừ',N'Phu Cu',N'Huyện Phù Cừ',N'Phu Cu District',N'phu cu',N'33',7),
	 ('336',N'Thái Bình',N'Thai Binh',N'Thành phố Thái Bình',N'Thai Binh City',N'thai binh',N'34',4),
	 ('338',N'Quỳnh Phụ',N'Quynh Phu',N'Huyện Quỳnh Phụ',N'Quynh Phu District',N'quynh phu',N'34',7),
	 ('339',N'Hưng Hà',N'Hung Ha',N'Huyện Hưng Hà',N'Hung Ha District',N'hung ha',N'34',7),
	 ('340',N'Đông Hưng',N'Dong Hung',N'Huyện Đông Hưng',N'Dong Hung District',N'dong hung',N'34',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('341',N'Thái Thụy',N'Thai Thuy',N'Huyện Thái Thụy',N'Thai Thuy District',N'thai thuy',N'34',7),
	 ('342',N'Tiền Hải',N'Tien Hai',N'Huyện Tiền Hải',N'Tien Hai District',N'tien hai',N'34',7),
	 ('343',N'Kiến Xương',N'Kien Xuong',N'Huyện Kiến Xương',N'Kien Xuong District',N'kien xuong',N'34',7),
	 ('344',N'Vũ Thư',N'Vu Thu',N'Huyện Vũ Thư',N'Vu Thu District',N'vu thu',N'34',7),
	 ('347',N'Phủ Lý',N'Phu Ly',N'Thành phố Phủ Lý',N'Phu Ly City',N'phu ly',N'35',4),
	 ('349',N'Duy Tiên',N'Duy Tien',N'Thị xã Duy Tiên',N'Duy Tien Town',N'duy tien',N'35',6),
	 ('350',N'Kim Bảng',N'Kim Bang',N'Huyện Kim Bảng',N'Kim Bang District',N'kim bang',N'35',7),
	 ('351',N'Thanh Liêm',N'Thanh Liem',N'Huyện Thanh Liêm',N'Thanh Liem District',N'thanh liem',N'35',7),
	 ('352',N'Bình Lục',N'Binh Luc',N'Huyện Bình Lục',N'Binh Luc District',N'binh luc',N'35',7),
	 ('353',N'Lý Nhân',N'Ly Nhan',N'Huyện Lý Nhân',N'Ly Nhan District',N'ly nhan',N'35',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('356',N'Nam Định',N'Nam Dinh',N'Thành phố Nam Định',N'Nam Dinh City',N'nam dinh',N'36',4),
	 ('358',N'Mỹ Lộc',N'My Loc',N'Huyện Mỹ Lộc',N'My Loc District',N'my loc',N'36',7),
	 ('359',N'Vụ Bản',N'Vu Ban',N'Huyện Vụ Bản',N'Vu Ban District',N'vu ban',N'36',7),
	 ('360',N'Ý Yên',N'Y Yen',N'Huyện Ý Yên',N'Y Yen District',N'y yen',N'36',7),
	 ('361',N'Nghĩa Hưng',N'Nghia Hung',N'Huyện Nghĩa Hưng',N'Nghia Hung District',N'nghia hung',N'36',7),
	 ('362',N'Nam Trực',N'Nam Truc',N'Huyện Nam Trực',N'Nam Truc District',N'nam truc',N'36',7),
	 ('363',N'Trực Ninh',N'Truc Ninh',N'Huyện Trực Ninh',N'Truc Ninh District',N'truc ninh',N'36',7),
	 ('364',N'Xuân Trường',N'Xuan Truong',N'Huyện Xuân Trường',N'Xuan Truong District',N'xuan truong',N'36',7),
	 ('365',N'Giao Thủy',N'Giao Thuy',N'Huyện Giao Thủy',N'Giao Thuy District',N'giao thuy',N'36',7),
	 ('366',N'Hải Hậu',N'Hai Hau',N'Huyện Hải Hậu',N'Hai Hau District',N'hai hau',N'36',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('369',N'Ninh Bình',N'Ninh Binh',N'Thành phố Ninh Bình',N'Ninh Binh City',N'ninh binh',N'37',4),
	 ('370',N'Tam Điệp',N'Tam Diep',N'Thành phố Tam Điệp',N'Tam Diep City',N'tam diep',N'37',4),
	 ('372',N'Nho Quan',N'Nho Quan',N'Huyện Nho Quan',N'Nho Quan District',N'nho quan',N'37',7),
	 ('373',N'Gia Viễn',N'Gia Vien',N'Huyện Gia Viễn',N'Gia Vien District',N'gia vien',N'37',7),
	 ('374',N'Hoa Lư',N'Hoa Lu',N'Huyện Hoa Lư',N'Hoa Lu District',N'hoa lu',N'37',7),
	 ('375',N'Yên Khánh',N'Yen Khanh',N'Huyện Yên Khánh',N'Yen Khanh District',N'yen khanh',N'37',7),
	 ('376',N'Kim Sơn',N'Kim Son',N'Huyện Kim Sơn',N'Kim Son District',N'kim son',N'37',7),
	 ('377',N'Yên Mô',N'Yen Mo',N'Huyện Yên Mô',N'Yen Mo District',N'yen mo',N'37',7),
	 ('380',N'Thanh Hóa',N'Thanh Hoa',N'Thành phố Thanh Hóa',N'Thanh Hoa City',N'thanh hoa',N'38',4),
	 ('381',N'Bỉm Sơn',N'Bim Son',N'Thị xã Bỉm Sơn',N'Bim Son Town',N'bim son',N'38',6);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('382',N'Sầm Sơn',N'Sam Son',N'Thành phố Sầm Sơn',N'Sam Son City',N'sam son',N'38',4),
	 ('384',N'Mường Lát',N'Muong Lat',N'Huyện Mường Lát',N'Muong Lat District',N'muong lat',N'38',7),
	 ('385',N'Quan Hóa',N'Quan Hoa',N'Huyện Quan Hóa',N'Quan Hoa District',N'quan hoa',N'38',7),
	 ('386',N'Bá Thước',N'Ba Thuoc',N'Huyện Bá Thước',N'Ba Thuoc District',N'ba thuoc',N'38',7),
	 ('387',N'Quan Sơn',N'Quan Son',N'Huyện Quan Sơn',N'Quan Son District',N'quan son',N'38',7),
	 ('388',N'Lang Chánh',N'Lang Chanh',N'Huyện Lang Chánh',N'Lang Chanh District',N'lang chanh',N'38',7),
	 ('389',N'Ngọc Lặc',N'Ngoc Lac',N'Huyện Ngọc Lặc',N'Ngoc Lac District',N'ngoc lac',N'38',7),
	 ('390',N'Cẩm Thủy',N'Cam Thuy',N'Huyện Cẩm Thủy',N'Cam Thuy District',N'cam thuy',N'38',7),
	 ('391',N'Thạch Thành',N'Thach Thanh',N'Huyện Thạch Thành',N'Thach Thanh District',N'thach thanh',N'38',7),
	 ('392',N'Hà Trung',N'Ha Trung',N'Huyện Hà Trung',N'Ha Trung District',N'ha trung',N'38',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('393',N'Vĩnh Lộc',N'Vinh Loc',N'Huyện Vĩnh Lộc',N'Vinh Loc District',N'vinh loc',N'38',7),
	 ('394',N'Yên Định',N'Yen Dinh',N'Huyện Yên Định',N'Yen Dinh District',N'yen dinh',N'38',7),
	 ('395',N'Thọ Xuân',N'Tho Xuan',N'Huyện Thọ Xuân',N'Tho Xuan District',N'tho xuan',N'38',7),
	 ('396',N'Thường Xuân',N'Thuong Xuan',N'Huyện Thường Xuân',N'Thuong Xuan District',N'thuong xuan',N'38',7),
	 ('397',N'Triệu Sơn',N'Trieu Son',N'Huyện Triệu Sơn',N'Trieu Son District',N'trieu son',N'38',7),
	 ('398',N'Thiệu Hóa',N'Thieu Hoa',N'Huyện Thiệu Hóa',N'Thieu Hoa District',N'thieu hoa',N'38',7),
	 ('399',N'Hoằng Hóa',N'Hoang Hoa',N'Huyện Hoằng Hóa',N'Hoang Hoa District',N'hoang hoa',N'38',7),
	 ('400',N'Hậu Lộc',N'Hau Loc',N'Huyện Hậu Lộc',N'Hau Loc District',N'hau loc',N'38',7),
	 ('401',N'Nga Sơn',N'Nga Son',N'Huyện Nga Sơn',N'Nga Son District',N'nga son',N'38',7),
	 ('402',N'Như Xuân',N'Nhu Xuan',N'Huyện Như Xuân',N'Nhu Xuan District',N'nhu xuan',N'38',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('403',N'Như Thanh',N'Nhu Thanh',N'Huyện Như Thanh',N'Nhu Thanh District',N'nhu thanh',N'38',7),
	 ('404',N'Nông Cống',N'Nong Cong',N'Huyện Nông Cống',N'Nong Cong District',N'nong cong',N'38',7),
	 ('405',N'Đông Sơn',N'Dong Son',N'Huyện Đông Sơn',N'Dong Son District',N'dong son',N'38',7),
	 ('406',N'Quảng Xương',N'Quang Xuong',N'Huyện Quảng Xương',N'Quang Xuong District',N'quang xuong',N'38',7),
	 ('407',N'Nghi Sơn',N'Nghi Son',N'Thị xã Nghi Sơn',N'Nghi Son Town',N'nghi son',N'38',6),
	 ('412',N'Vinh',N'Vinh',N'Thành phố Vinh',N'Vinh City',N'vinh',N'40',4),
	 ('413',N'Cửa Lò',N'Cua Lo',N'Thị xã Cửa Lò',N'Cua Lo Town',N'cua lo',N'40',6),
	 ('414',N'Thái Hoà',N'Thai Hoa',N'Thị xã Thái Hoà',N'Thai Hoa Town',N'thai hoa',N'40',6),
	 ('415',N'Quế Phong',N'Que Phong',N'Huyện Quế Phong',N'Que Phong District',N'que phong',N'40',7),
	 ('416',N'Quỳ Châu',N'Quy Chau',N'Huyện Quỳ Châu',N'Quy Chau District',N'quy chau',N'40',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('417',N'Kỳ Sơn',N'Ky Son',N'Huyện Kỳ Sơn',N'Ky Son District',N'ky son',N'40',7),
	 ('418',N'Tương Dương',N'Tuong Duong',N'Huyện Tương Dương',N'Tuong Duong District',N'tuong duong',N'40',7),
	 ('419',N'Nghĩa Đàn',N'Nghia Dan',N'Huyện Nghĩa Đàn',N'Nghia Dan District',N'nghia dan',N'40',7),
	 ('420',N'Quỳ Hợp',N'Quy Hop',N'Huyện Quỳ Hợp',N'Quy Hop District',N'quy hop',N'40',7),
	 ('421',N'Quỳnh Lưu',N'Quynh Luu',N'Huyện Quỳnh Lưu',N'Quynh Luu District',N'quynh luu',N'40',7),
	 ('422',N'Con Cuông',N'Con Cuong',N'Huyện Con Cuông',N'Con Cuong District',N'con cuong',N'40',7),
	 ('423',N'Tân Kỳ',N'Tan Ky',N'Huyện Tân Kỳ',N'Tan Ky District',N'tan ky',N'40',7),
	 ('424',N'Anh Sơn',N'Anh Son',N'Huyện Anh Sơn',N'Anh Son District',N'anh son',N'40',7),
	 ('425',N'Diễn Châu',N'Dien Chau',N'Huyện Diễn Châu',N'Dien Chau District',N'dien chau',N'40',7),
	 ('426',N'Yên Thành',N'Yen Thanh',N'Huyện Yên Thành',N'Yen Thanh District',N'yen thanh',N'40',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('427',N'Đô Lương',N'Do Luong',N'Huyện Đô Lương',N'Do Luong District',N'do luong',N'40',7),
	 ('428',N'Thanh Chương',N'Thanh Chuong',N'Huyện Thanh Chương',N'Thanh Chuong District',N'thanh chuong',N'40',7),
	 ('429',N'Nghi Lộc',N'Nghi Loc',N'Huyện Nghi Lộc',N'Nghi Loc District',N'nghi loc',N'40',7),
	 ('430',N'Nam Đàn',N'Nam Dan',N'Huyện Nam Đàn',N'Nam Dan District',N'nam dan',N'40',7),
	 ('431',N'Hưng Nguyên',N'Hung Nguyen',N'Huyện Hưng Nguyên',N'Hung Nguyen District',N'hung nguyen',N'40',7),
	 ('432',N'Hoàng Mai',N'Hoang Mai',N'Thị xã Hoàng Mai',N'Hoang Mai Town',N'hoang mai',N'40',6),
	 ('436',N'Hà Tĩnh',N'Ha Tinh',N'Thành phố Hà Tĩnh',N'Ha Tinh City',N'ha tinh',N'42',4),
	 ('437',N'Hồng Lĩnh',N'Hong Linh',N'Thị xã Hồng Lĩnh',N'Hong Linh Town',N'hong linh',N'42',6),
	 ('439',N'Hương Sơn',N'Huong Son',N'Huyện Hương Sơn',N'Huong Son District',N'huong son',N'42',7),
	 ('440',N'Đức Thọ',N'Duc Tho',N'Huyện Đức Thọ',N'Duc Tho District',N'duc tho',N'42',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('441',N'Vũ Quang',N'Vu Quang',N'Huyện Vũ Quang',N'Vu Quang District',N'vu quang',N'42',7),
	 ('442',N'Nghi Xuân',N'Nghi Xuan',N'Huyện Nghi Xuân',N'Nghi Xuan District',N'nghi xuan',N'42',7),
	 ('443',N'Can Lộc',N'Can Loc',N'Huyện Can Lộc',N'Can Loc District',N'can loc',N'42',7),
	 ('444',N'Hương Khê',N'Huong Khe',N'Huyện Hương Khê',N'Huong Khe District',N'huong khe',N'42',7),
	 ('445',N'Thạch Hà',N'Thach Ha',N'Huyện Thạch Hà',N'Thach Ha District',N'thach ha',N'42',7),
	 ('446',N'Cẩm Xuyên',N'Cam Xuyen',N'Huyện Cẩm Xuyên',N'Cam Xuyen District',N'cam xuyen',N'42',7),
	 ('447',N'Kỳ Anh',N'Ky Anh',N'Huyện Kỳ Anh',N'Ky Anh District',N'ky anh',N'42',7),
	 ('448',N'Lộc Hà',N'Loc Ha',N'Huyện Lộc Hà',N'Loc Ha District',N'loc ha',N'42',7),
	 ('449',N'Kỳ Anh',N'Ky Anh',N'Thị xã Kỳ Anh',N'Ky Anh Town',N'ky anh',N'42',6),
	 ('450',N'Đồng Hới',N'Dong Hoi',N'Thành phố Đồng Hới',N'Dong Hoi City',N'dong hoi',N'44',4);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('452',N'Minh Hóa',N'Minh Hoa',N'Huyện Minh Hóa',N'Minh Hoa District',N'minh hoa',N'44',7),
	 ('453',N'Tuyên Hóa',N'Tuyen Hoa',N'Huyện Tuyên Hóa',N'Tuyen Hoa District',N'tuyen hoa',N'44',7),
	 ('454',N'Quảng Trạch',N'Quang Trach',N'Huyện Quảng Trạch',N'Quang Trach District',N'quang trach',N'44',7),
	 ('455',N'Bố Trạch',N'Bo Trach',N'Huyện Bố Trạch',N'Bo Trach District',N'bo trach',N'44',7),
	 ('456',N'Quảng Ninh',N'Quang Ninh',N'Huyện Quảng Ninh',N'Quang Ninh District',N'quang ninh',N'44',7),
	 ('457',N'Lệ Thủy',N'Le Thuy',N'Huyện Lệ Thủy',N'Le Thuy District',N'le thuy',N'44',7),
	 ('458',N'Ba Đồn',N'Ba Don',N'Thị xã Ba Đồn',N'Ba Don Town',N'ba don',N'44',6),
	 ('461',N'Đông Hà',N'Dong Ha',N'Thành phố Đông Hà',N'Dong Ha City',N'dong ha',N'45',4),
	 ('462',N'Quảng Trị',N'Quang Tri',N'Thị xã Quảng Trị',N'Quang Tri Town',N'quang tri',N'45',6),
	 ('464',N'Vĩnh Linh',N'Vinh Linh',N'Huyện Vĩnh Linh',N'Vinh Linh District',N'vinh linh',N'45',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('465',N'Hướng Hóa',N'Huong Hoa',N'Huyện Hướng Hóa',N'Huong Hoa District',N'huong hoa',N'45',7),
	 ('466',N'Gio Linh',N'Gio Linh',N'Huyện Gio Linh',N'Gio Linh District',N'gio linh',N'45',7),
	 ('467',N'Đa Krông',N'Da Krong',N'Huyện Đa Krông',N'Da Krong District',N'da krong',N'45',7),
	 ('468',N'Cam Lộ',N'Cam Lo',N'Huyện Cam Lộ',N'Cam Lo District',N'cam lo',N'45',7),
	 ('469',N'Triệu Phong',N'Trieu Phong',N'Huyện Triệu Phong',N'Trieu Phong District',N'trieu phong',N'45',7),
	 ('470',N'Hải Lăng',N'Hai Lang',N'Huyện Hải Lăng',N'Hai Lang District',N'hai lang',N'45',7),
	 ('471',N'Cồn Cỏ',N'Con Co',N'Huyện Cồn Cỏ',N'Con Co District',N'con co',N'45',7),
	 ('474',N'Huế',N'Hue',N'Thành phố Huế',N'Hue City',N'hue',N'46',4),
	 ('476',N'Phong Điền',N'Phong Dien',N'Huyện Phong Điền',N'Phong Dien District',N'phong dien',N'46',7),
	 ('477',N'Quảng Điền',N'Quang Dien',N'Huyện Quảng Điền',N'Quang Dien District',N'quang dien',N'46',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('478',N'Phú Vang',N'Phu Vang',N'Huyện Phú Vang',N'Phu Vang District',N'phu vang',N'46',7),
	 ('479',N'Hương Thủy',N'Huong Thuy',N'Thị xã Hương Thủy',N'Huong Thuy Town',N'huong thuy',N'46',6),
	 ('480',N'Hương Trà',N'Huong Tra',N'Thị xã Hương Trà',N'Huong Tra Town',N'huong tra',N'46',6),
	 ('481',N'A Lưới',N'A Luoi',N'Huyện A Lưới',N'A Luoi District',N'a luoi',N'46',7),
	 ('482',N'Phú Lộc',N'Phu Loc',N'Huyện Phú Lộc',N'Phu Loc District',N'phu loc',N'46',7),
	 ('483',N'Nam Đông',N'Nam Dong',N'Huyện Nam Đông',N'Nam Dong District',N'nam dong',N'46',7),
	 ('490',N'Liên Chiểu',N'Lien Chieu',N'Quận Liên Chiểu',N'Lien Chieu District',N'lien chieu',N'48',5),
	 ('491',N'Thanh Khê',N'Thanh Khe',N'Quận Thanh Khê',N'Thanh Khe District',N'thanh khe',N'48',5),
	 ('492',N'Hải Châu',N'Hai Chau',N'Quận Hải Châu',N'Hai Chau District',N'hai chau',N'48',5),
	 ('493',N'Sơn Trà',N'Son Tra',N'Quận Sơn Trà',N'Son Tra District',N'son tra',N'48',5);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('494',N'Ngũ Hành Sơn',N'Ngu Hanh Son',N'Quận Ngũ Hành Sơn',N'Ngu Hanh Son District',N'ngu hanh son',N'48',5),
	 ('495',N'Cẩm Lệ',N'Cam Le',N'Quận Cẩm Lệ',N'Cam Le District',N'cam le',N'48',5),
	 ('497',N'Hòa Vang',N'Hoa Vang',N'Huyện Hòa Vang',N'Hoa Vang District',N'hoa vang',N'48',7),
	 ('498',N'Hoàng Sa',N'Hoang Sa',N'Huyện Hoàng Sa',N'Hoang Sa District',N'hoang sa',N'48',7),
	 ('502',N'Tam Kỳ',N'Tam Ky',N'Thành phố Tam Kỳ',N'Tam Ky City',N'tam ky',N'49',4),
	 ('503',N'Hội An',N'Hoi An',N'Thành phố Hội An',N'Hoi An City',N'hoi an',N'49',4),
	 ('504',N'Tây Giang',N'Tay Giang',N'Huyện Tây Giang',N'Tay Giang District',N'tay giang',N'49',7),
	 ('505',N'Đông Giang',N'Dong Giang',N'Huyện Đông Giang',N'Dong Giang District',N'dong giang',N'49',7),
	 ('506',N'Đại Lộc',N'Dai Loc',N'Huyện Đại Lộc',N'Dai Loc District',N'dai loc',N'49',7),
	 ('507',N'Điện Bàn',N'Dien Ban',N'Thị xã Điện Bàn',N'Dien Ban Town',N'dien ban',N'49',6);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('508',N'Duy Xuyên',N'Duy Xuyen',N'Huyện Duy Xuyên',N'Duy Xuyen District',N'duy xuyen',N'49',7),
	 ('509',N'Quế Sơn',N'Que Son',N'Huyện Quế Sơn',N'Que Son District',N'que son',N'49',7),
	 ('510',N'Nam Giang',N'Nam Giang',N'Huyện Nam Giang',N'Nam Giang District',N'nam giang',N'49',7),
	 ('511',N'Phước Sơn',N'Phuoc Son',N'Huyện Phước Sơn',N'Phuoc Son District',N'phuoc son',N'49',7),
	 ('512',N'Hiệp Đức',N'Hiep Duc',N'Huyện Hiệp Đức',N'Hiep Duc District',N'hiep duc',N'49',7),
	 ('513',N'Thăng Bình',N'Thang Binh',N'Huyện Thăng Bình',N'Thang Binh District',N'thang binh',N'49',7),
	 ('514',N'Tiên Phước',N'Tien Phuoc',N'Huyện Tiên Phước',N'Tien Phuoc District',N'tien phuoc',N'49',7),
	 ('515',N'Bắc Trà My',N'Bac Tra My',N'Huyện Bắc Trà My',N'Bac Tra My District',N'bac tra my',N'49',7),
	 ('516',N'Nam Trà My',N'Nam Tra My',N'Huyện Nam Trà My',N'Nam Tra My District',N'nam tra my',N'49',7),
	 ('517',N'Núi Thành',N'Nui Thanh',N'Huyện Núi Thành',N'Nui Thanh District',N'nui thanh',N'49',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('518',N'Phú Ninh',N'Phu Ninh',N'Huyện Phú Ninh',N'Phu Ninh District',N'phu ninh',N'49',7),
	 ('519',N'Nông Sơn',N'Nong Son',N'Huyện Nông Sơn',N'Nong Son District',N'nong son',N'49',7),
	 ('522',N'Quảng Ngãi',N'Quang Ngai',N'Thành phố Quảng Ngãi',N'Quang Ngai City',N'quang ngai',N'51',4),
	 ('524',N'Bình Sơn',N'Binh Son',N'Huyện Bình Sơn',N'Binh Son District',N'binh son',N'51',7),
	 ('525',N'Trà Bồng',N'Tra Bong',N'Huyện Trà Bồng',N'Tra Bong District',N'tra bong',N'51',7),
	 ('527',N'Sơn Tịnh',N'Son Tinh',N'Huyện Sơn Tịnh',N'Son Tinh District',N'son tinh',N'51',7),
	 ('528',N'Tư Nghĩa',N'Tu Nghia',N'Huyện Tư Nghĩa',N'Tu Nghia District',N'tu nghia',N'51',7),
	 ('529',N'Sơn Hà',N'Son Ha',N'Huyện Sơn Hà',N'Son Ha District',N'son ha',N'51',7),
	 ('530',N'Sơn Tây',N'Son Tay',N'Huyện Sơn Tây',N'Son Tay District',N'son tay',N'51',7),
	 ('531',N'Minh Long',N'Minh Long',N'Huyện Minh Long',N'Minh Long District',N'minh long',N'51',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('532',N'Nghĩa Hành',N'Nghia Hanh',N'Huyện Nghĩa Hành',N'Nghia Hanh District',N'nghia hanh',N'51',7),
	 ('533',N'Mộ Đức',N'Mo Duc',N'Huyện Mộ Đức',N'Mo Duc District',N'mo duc',N'51',7),
	 ('534',N'Đức Phổ',N'Duc Pho',N'Thị xã Đức Phổ',N'Duc Pho Town',N'duc pho',N'51',6),
	 ('535',N'Ba Tơ',N'Ba To',N'Huyện Ba Tơ',N'Ba To District',N'ba to',N'51',7),
	 ('536',N'Lý Sơn',N'Ly Son',N'Huyện Lý Sơn',N'Ly Son District',N'ly son',N'51',7),
	 ('540',N'Quy Nhơn',N'Quy Nhon',N'Thành phố Quy Nhơn',N'Quy Nhon City',N'quy nhon',N'52',4),
	 ('542',N'An Lão',N'An Lao',N'Huyện An Lão',N'An Lao District',N'an lao',N'52',7),
	 ('543',N'Hoài Nhơn',N'Hoai Nhon',N'Thị xã Hoài Nhơn',N'Hoai Nhon Town',N'hoai nhon',N'52',6),
	 ('544',N'Hoài Ân',N'Hoai An',N'Huyện Hoài Ân',N'Hoai An District',N'hoai an',N'52',7),
	 ('545',N'Phù Mỹ',N'Phu My',N'Huyện Phù Mỹ',N'Phu My District',N'phu my',N'52',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('546',N'Vĩnh Thạnh',N'Vinh Thanh',N'Huyện Vĩnh Thạnh',N'Vinh Thanh District',N'vinh thanh',N'52',7),
	 ('547',N'Tây Sơn',N'Tay Son',N'Huyện Tây Sơn',N'Tay Son District',N'tay son',N'52',7),
	 ('548',N'Phù Cát',N'Phu Cat',N'Huyện Phù Cát',N'Phu Cat District',N'phu cat',N'52',7),
	 ('549',N'An Nhơn',N'An Nhon',N'Thị xã An Nhơn',N'An Nhon Town',N'an nhon',N'52',6),
	 ('550',N'Tuy Phước',N'Tuy Phuoc',N'Huyện Tuy Phước',N'Tuy Phuoc District',N'tuy phuoc',N'52',7),
	 ('551',N'Vân Canh',N'Van Canh',N'Huyện Vân Canh',N'Van Canh District',N'van canh',N'52',7),
	 ('555',N'Tuy Hoà',N'Tuy Hoa',N'Thành phố Tuy Hoà',N'Tuy Hoa City',N'tuy hoa',N'54',4),
	 ('557',N'Sông Cầu',N'Song Cau',N'Thị xã Sông Cầu',N'Song Cau Town',N'song cau',N'54',6),
	 ('558',N'Đồng Xuân',N'Dong Xuan',N'Huyện Đồng Xuân',N'Dong Xuan District',N'dong xuan',N'54',7),
	 ('559',N'Tuy An',N'Tuy An',N'Huyện Tuy An',N'Tuy An District',N'tuy an',N'54',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('560',N'Sơn Hòa',N'Son Hoa',N'Huyện Sơn Hòa',N'Son Hoa District',N'son hoa',N'54',7),
	 ('561',N'Sông Hinh',N'Song Hinh',N'Huyện Sông Hinh',N'Song Hinh District',N'song hinh',N'54',7),
	 ('562',N'Tây Hoà',N'Tay Hoa',N'Huyện Tây Hoà',N'Tay Hoa District',N'tay hoa',N'54',7),
	 ('563',N'Phú Hoà',N'Phu Hoa',N'Huyện Phú Hoà',N'Phu Hoa District',N'phu hoa',N'54',7),
	 ('564',N'Đông Hòa',N'Dong Hoa',N'Thị xã Đông Hòa',N'Dong Hoa Town',N'dong hoa',N'54',6),
	 ('568',N'Nha Trang',N'Nha Trang',N'Thành phố Nha Trang',N'Nha Trang City',N'nha trang',N'56',4),
	 ('569',N'Cam Ranh',N'Cam Ranh',N'Thành phố Cam Ranh',N'Cam Ranh City',N'cam ranh',N'56',4),
	 ('570',N'Cam Lâm',N'Cam Lam',N'Huyện Cam Lâm',N'Cam Lam District',N'cam lam',N'56',7),
	 ('571',N'Vạn Ninh',N'Van Ninh',N'Huyện Vạn Ninh',N'Van Ninh District',N'van ninh',N'56',7),
	 ('572',N'Ninh Hòa',N'Ninh Hoa',N'Thị xã Ninh Hòa',N'Ninh Hoa Town',N'ninh hoa',N'56',6);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('573',N'Khánh Vĩnh',N'Khanh Vinh',N'Huyện Khánh Vĩnh',N'Khanh Vinh District',N'khanh vinh',N'56',7),
	 ('574',N'Diên Khánh',N'Dien Khanh',N'Huyện Diên Khánh',N'Dien Khanh District',N'dien khanh',N'56',7),
	 ('575',N'Khánh Sơn',N'Khanh Son',N'Huyện Khánh Sơn',N'Khanh Son District',N'khanh son',N'56',7),
	 ('576',N'Trường Sa',N'Truong Sa',N'Huyện Trường Sa',N'Truong Sa District',N'truong sa',N'56',7),
	 ('582',N'Phan Rang-Tháp Chàm',N'Phan Rang-Thap Cham',N'Thành phố Phan Rang-Tháp Chàm',N'Phan Rang-Thap Cham City',N'phan rang-thap cham',N'58',4),
	 ('584',N'Bác Ái',N'Bac Ai',N'Huyện Bác Ái',N'Bac Ai District',N'bac ai',N'58',7),
	 ('585',N'Ninh Sơn',N'Ninh Son',N'Huyện Ninh Sơn',N'Ninh Son District',N'ninh son',N'58',7),
	 ('586',N'Ninh Hải',N'Ninh Hai',N'Huyện Ninh Hải',N'Ninh Hai District',N'ninh hai',N'58',7),
	 ('587',N'Ninh Phước',N'Ninh Phuoc',N'Huyện Ninh Phước',N'Ninh Phuoc District',N'ninh phuoc',N'58',7),
	 ('588',N'Thuận Bắc',N'Thuan Bac',N'Huyện Thuận Bắc',N'Thuan Bac District',N'thuan bac',N'58',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('589',N'Thuận Nam',N'Thuan Nam',N'Huyện Thuận Nam',N'Thuan Nam District',N'thuan nam',N'58',7),
	 ('593',N'Phan Thiết',N'Phan Thiet',N'Thành phố Phan Thiết',N'Phan Thiet City',N'phan thiet',N'60',4),
	 ('594',N'La Gi',N'La Gi',N'Thị xã La Gi',N'La Gi Town',N'la gi',N'60',6),
	 ('595',N'Tuy Phong',N'Tuy Phong',N'Huyện Tuy Phong',N'Tuy Phong District',N'tuy phong',N'60',7),
	 ('596',N'Bắc Bình',N'Bac Binh',N'Huyện Bắc Bình',N'Bac Binh District',N'bac binh',N'60',7),
	 ('597',N'Hàm Thuận Bắc',N'Ham Thuan Bac',N'Huyện Hàm Thuận Bắc',N'Ham Thuan Bac District',N'ham thuan bac',N'60',7),
	 ('598',N'Hàm Thuận Nam',N'Ham Thuan Nam',N'Huyện Hàm Thuận Nam',N'Ham Thuan Nam District',N'ham thuan nam',N'60',7),
	 ('599',N'Tánh Linh',N'Tanh Linh',N'Huyện Tánh Linh',N'Tanh Linh District',N'tanh linh',N'60',7),
	 ('600',N'Đức Linh',N'Duc Linh',N'Huyện Đức Linh',N'Duc Linh District',N'duc linh',N'60',7),
	 ('601',N'Hàm Tân',N'Ham Tan',N'Huyện Hàm Tân',N'Ham Tan District',N'ham tan',N'60',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('602',N'Phú Quí',N'Phu Qui',N'Huyện Phú Quí',N'Phu Qui District',N'phu qui',N'60',7),
	 ('608',N'Kon Tum',N'Kon Tum',N'Thành phố Kon Tum',N'Kon Tum City',N'kon tum',N'62',4),
	 ('610',N'Đắk Glei',N'Dak Glei',N'Huyện Đắk Glei',N'Dak Glei District',N'dak glei',N'62',7),
	 ('611',N'Ngọc Hồi',N'Ngoc Hoi',N'Huyện Ngọc Hồi',N'Ngoc Hoi District',N'ngoc hoi',N'62',7),
	 ('612',N'Đắk Tô',N'Dak To',N'Huyện Đắk Tô',N'Dak To District',N'dak to',N'62',7),
	 ('613',N'Kon Plông',N'Kon Plong',N'Huyện Kon Plông',N'Kon Plong District',N'kon plong',N'62',7),
	 ('614',N'Kon Rẫy',N'Kon Ray',N'Huyện Kon Rẫy',N'Kon Ray District',N'kon ray',N'62',7),
	 ('615',N'Đắk Hà',N'Dak Ha',N'Huyện Đắk Hà',N'Dak Ha District',N'dak ha',N'62',7),
	 ('616',N'Sa Thầy',N'Sa Thay',N'Huyện Sa Thầy',N'Sa Thay District',N'sa thay',N'62',7),
	 ('617',N'Tu Mơ Rông',N'Tu Mo Rong',N'Huyện Tu Mơ Rông',N'Tu Mo Rong District',N'tu mo rong',N'62',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('618',N'Ia H'' Drai',N'Ia H'' Drai',N'Huyện Ia H'' Drai',N'Ia H'' Drai District',N'ia h'' drai',N'62',7),
	 ('622',N'Pleiku',N'Pleiku',N'Thành phố Pleiku',N'Pleiku City',N'pleiku',N'64',4),
	 ('623',N'An Khê',N'An Khe',N'Thị xã An Khê',N'An Khe Town',N'an khe',N'64',6),
	 ('624',N'Ayun Pa',N'Ayun Pa',N'Thị xã Ayun Pa',N'Ayun Pa Town',N'ayun pa',N'64',6),
	 ('625',N'KBang',N'KBang',N'Huyện KBang',N'KBang District',N'kbang',N'64',7),
	 ('626',N'Đăk Đoa',N'Dak Doa',N'Huyện Đăk Đoa',N'Dak Doa District',N'dak doa',N'64',7),
	 ('627',N'Chư Păh',N'Chu Pah',N'Huyện Chư Păh',N'Chu Pah District',N'chu pah',N'64',7),
	 ('628',N'Ia Grai',N'Ia Grai',N'Huyện Ia Grai',N'Ia Grai District',N'ia grai',N'64',7),
	 ('629',N'Mang Yang',N'Mang Yang',N'Huyện Mang Yang',N'Mang Yang District',N'mang yang',N'64',7),
	 ('630',N'Kông Chro',N'Kong Chro',N'Huyện Kông Chro',N'Kong Chro District',N'kong chro',N'64',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('631',N'Đức Cơ',N'Duc Co',N'Huyện Đức Cơ',N'Duc Co District',N'duc co',N'64',7),
	 ('632',N'Chư Prông',N'Chu Prong',N'Huyện Chư Prông',N'Chu Prong District',N'chu prong',N'64',7),
	 ('633',N'Chư Sê',N'Chu Se',N'Huyện Chư Sê',N'Chu Se District',N'chu se',N'64',7),
	 ('634',N'Đăk Pơ',N'Dak Po',N'Huyện Đăk Pơ',N'Dak Po District',N'dak po',N'64',7),
	 ('635',N'Ia Pa',N'Ia Pa',N'Huyện Ia Pa',N'Ia Pa District',N'ia pa',N'64',7),
	 ('637',N'Krông Pa',N'Krong Pa',N'Huyện Krông Pa',N'Krong Pa District',N'krong pa',N'64',7),
	 ('638',N'Phú Thiện',N'Phu Thien',N'Huyện Phú Thiện',N'Phu Thien District',N'phu thien',N'64',7),
	 ('639',N'Chư Pưh',N'Chu Puh',N'Huyện Chư Pưh',N'Chu Puh District',N'chu puh',N'64',7),
	 ('643',N'Buôn Ma Thuột',N'Buon Ma Thuot',N'Thành phố Buôn Ma Thuột',N'Buon Ma Thuot City',N'buon ma thuot',N'66',4),
	 ('644',N'Buôn Hồ',N'Buon Ho',N'Thị xã Buôn Hồ',N'Buon Ho Town',N'buon ho',N'66',6);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('645',N'Ea H''leo',N'Ea H''leo',N'Huyện Ea H''leo',N'Ea H''leo District',N'ea h''leo',N'66',7),
	 ('646',N'Ea Súp',N'Ea Sup',N'Huyện Ea Súp',N'Ea Sup District',N'ea sup',N'66',7),
	 ('647',N'Buôn Đôn',N'Buon Don',N'Huyện Buôn Đôn',N'Buon Don District',N'buon don',N'66',7),
	 ('648',N'Cư M''gar',N'Cu M''gar',N'Huyện Cư M''gar',N'Cu M''gar District',N'cu m''gar',N'66',7),
	 ('649',N'Krông Búk',N'Krong Buk',N'Huyện Krông Búk',N'Krong Buk District',N'krong buk',N'66',7),
	 ('650',N'Krông Năng',N'Krong Nang',N'Huyện Krông Năng',N'Krong Nang District',N'krong nang',N'66',7),
	 ('651',N'Ea Kar',N'Ea Kar',N'Huyện Ea Kar',N'Ea Kar District',N'ea kar',N'66',7),
	 ('652',N'M''Đrắk',N'M''Drak',N'Huyện M''Đrắk',N'M''Drak District',N'm''drak',N'66',7),
	 ('653',N'Krông Bông',N'Krong Bong',N'Huyện Krông Bông',N'Krong Bong District',N'krong bong',N'66',7),
	 ('654',N'Krông Pắc',N'Krong Pac',N'Huyện Krông Pắc',N'Krong Pac District',N'krong pac',N'66',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('655',N'Krông A Na',N'Krong A Na',N'Huyện Krông A Na',N'Krong A Na District',N'krong a na',N'66',7),
	 ('656',N'Lắk',N'Lak',N'Huyện Lắk',N'Lak District',N'lak',N'66',7),
	 ('657',N'Cư Kuin',N'Cu Kuin',N'Huyện Cư Kuin',N'Cu Kuin District',N'cu kuin',N'66',7),
	 ('660',N'Gia Nghĩa',N'Gia Nghia',N'Thành phố Gia Nghĩa',N'Gia Nghia City',N'gia nghia',N'67',4),
	 ('661',N'Đăk Glong',N'Dak Glong',N'Huyện Đăk Glong',N'Dak Glong District',N'dak glong',N'67',7),
	 ('662',N'Cư Jút',N'Cu Jut',N'Huyện Cư Jút',N'Cu Jut District',N'cu jut',N'67',7),
	 ('663',N'Đắk Mil',N'Dak Mil',N'Huyện Đắk Mil',N'Dak Mil District',N'dak mil',N'67',7),
	 ('664',N'Krông Nô',N'Krong No',N'Huyện Krông Nô',N'Krong No District',N'krong no',N'67',7),
	 ('665',N'Đắk Song',N'Dak Song',N'Huyện Đắk Song',N'Dak Song District',N'dak song',N'67',7),
	 ('666',N'Đắk R''Lấp',N'Dak R''Lap',N'Huyện Đắk R''Lấp',N'Dak R''Lap District',N'dak r''lap',N'67',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('667',N'Tuy Đức',N'Tuy Duc',N'Huyện Tuy Đức',N'Tuy Duc District',N'tuy duc',N'67',7),
	 ('672',N'Đà Lạt',N'Da Lat',N'Thành phố Đà Lạt',N'Da Lat City',N'da lat',N'68',4),
	 ('673',N'Bảo Lộc',N'Bao Loc',N'Thành phố Bảo Lộc',N'Bao Loc City',N'bao loc',N'68',4),
	 ('674',N'Đam Rông',N'Dam Rong',N'Huyện Đam Rông',N'Dam Rong District',N'dam rong',N'68',7),
	 ('675',N'Lạc Dương',N'Lac Duong',N'Huyện Lạc Dương',N'Lac Duong District',N'lac duong',N'68',7),
	 ('676',N'Lâm Hà',N'Lam Ha',N'Huyện Lâm Hà',N'Lam Ha District',N'lam ha',N'68',7),
	 ('677',N'Đơn Dương',N'Don Duong',N'Huyện Đơn Dương',N'Don Duong District',N'don duong',N'68',7),
	 ('678',N'Đức Trọng',N'Duc Trong',N'Huyện Đức Trọng',N'Duc Trong District',N'duc trong',N'68',7),
	 ('679',N'Di Linh',N'Di Linh',N'Huyện Di Linh',N'Di Linh District',N'di linh',N'68',7),
	 ('680',N'Bảo Lâm',N'Bao Lam',N'Huyện Bảo Lâm',N'Bao Lam District',N'bao lam',N'68',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('681',N'Đạ Huoai',N'Da Huoai',N'Huyện Đạ Huoai',N'Da Huoai District',N'da huoai',N'68',7),
	 ('682',N'Đạ Tẻh',N'Da Teh',N'Huyện Đạ Tẻh',N'Da Teh District',N'da teh',N'68',7),
	 ('683',N'Cát Tiên',N'Cat Tien',N'Huyện Cát Tiên',N'Cat Tien District',N'cat tien',N'68',7),
	 ('688',N'Phước Long',N'Phuoc Long',N'Thị xã Phước Long',N'Phuoc Long Town',N'phuoc long',N'70',6),
	 ('689',N'Đồng Xoài',N'Dong Xoai',N'Thành phố Đồng Xoài',N'Dong Xoai City',N'dong xoai',N'70',4),
	 ('690',N'Bình Long',N'Binh Long',N'Thị xã Bình Long',N'Binh Long Town',N'binh long',N'70',6),
	 ('691',N'Bù Gia Mập',N'Bu Gia Map',N'Huyện Bù Gia Mập',N'Bu Gia Map District',N'bu gia map',N'70',7),
	 ('692',N'Lộc Ninh',N'Loc Ninh',N'Huyện Lộc Ninh',N'Loc Ninh District',N'loc ninh',N'70',7),
	 ('693',N'Bù Đốp',N'Bu Dop',N'Huyện Bù Đốp',N'Bu Dop District',N'bu dop',N'70',7),
	 ('694',N'Hớn Quản',N'Hon Quan',N'Huyện Hớn Quản',N'Hon Quan District',N'hon quan',N'70',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('695',N'Đồng Phú',N'Dong Phu',N'Huyện Đồng Phú',N'Dong Phu District',N'dong phu',N'70',7),
	 ('696',N'Bù Đăng',N'Bu Dang',N'Huyện Bù Đăng',N'Bu Dang District',N'bu dang',N'70',7),
	 ('697',N'Chơn Thành',N'Chon Thanh',N'Thị xã Chơn Thành',N'Chon Thanh Town',N'chon thanh',N'70',6),
	 ('698',N'Phú Riềng',N'Phu Rieng',N'Huyện Phú Riềng',N'Phu Rieng District',N'phu rieng',N'70',7),
	 ('703',N'Tây Ninh',N'Tay Ninh',N'Thành phố Tây Ninh',N'Tay Ninh City',N'tay ninh',N'72',4),
	 ('705',N'Tân Biên',N'Tan Bien',N'Huyện Tân Biên',N'Tan Bien District',N'tan bien',N'72',7),
	 ('706',N'Tân Châu',N'Tan Chau',N'Huyện Tân Châu',N'Tan Chau District',N'tan chau',N'72',7),
	 ('707',N'Dương Minh Châu',N'Duong Minh Chau',N'Huyện Dương Minh Châu',N'Duong Minh Chau District',N'duong minh chau',N'72',7),
	 ('708',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District',N'chau thanh',N'72',7),
	 ('709',N'Hòa Thành',N'Hoa Thanh',N'Thị xã Hòa Thành',N'Hoa Thanh Town',N'hoa thanh',N'72',6);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('711',N'Bến Cầu',N'Ben Cau',N'Huyện Bến Cầu',N'Ben Cau District',N'ben cau',N'72',7),
	 ('712',N'Trảng Bàng',N'Trang Bang',N'Thị xã Trảng Bàng',N'Trang Bang Town',N'trang bang',N'72',6),
	 ('718',N'Thủ Dầu Một',N'Thu Dau Mot',N'Thành phố Thủ Dầu Một',N'Thu Dau Mot City',N'thu dau mot',N'74',4),
	 ('719',N'Bàu Bàng',N'Bau Bang',N'Huyện Bàu Bàng',N'Bau Bang District',N'bau bang',N'74',7),
	 ('720',N'Dầu Tiếng',N'Dau Tieng',N'Huyện Dầu Tiếng',N'Dau Tieng District',N'dau tieng',N'74',7),
	 ('721',N'Bến Cát',N'Ben Cat',N'Thị xã Bến Cát',N'Ben Cat Town',N'ben cat',N'74',6),
	 ('722',N'Phú Giáo',N'Phu Giao',N'Huyện Phú Giáo',N'Phu Giao District',N'phu giao',N'74',7),
	 ('723',N'Tân Uyên',N'Tan Uyen',N'Thị xã Tân Uyên',N'Tan Uyen Town',N'tan uyen',N'74',6),
	 ('724',N'Dĩ An',N'Di An',N'Thành phố Dĩ An',N'Di An City',N'di an',N'74',4),
	 ('726',N'Bắc Tân Uyên',N'Bac Tan Uyen',N'Huyện Bắc Tân Uyên',N'Bac Tan Uyen District',N'bac tan uyen',N'74',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('731',N'Biên Hòa',N'Bien Hoa',N'Thành phố Biên Hòa',N'Bien Hoa City',N'bien hoa',N'75',4),
	 ('732',N'Long Khánh',N'Long Khanh',N'Thành phố Long Khánh',N'Long Khanh City',N'long khanh',N'75',4),
	 ('734',N'Tân Phú',N'Tan Phu',N'Huyện Tân Phú',N'Tan Phu District',N'tan phu',N'75',7),
	 ('735',N'Vĩnh Cửu',N'Vinh Cuu',N'Huyện Vĩnh Cửu',N'Vinh Cuu District',N'vinh cuu',N'75',7),
	 ('736',N'Định Quán',N'Dinh Quan',N'Huyện Định Quán',N'Dinh Quan District',N'dinh quan',N'75',7),
	 ('737',N'Trảng Bom',N'Trang Bom',N'Huyện Trảng Bom',N'Trang Bom District',N'trang bom',N'75',7),
	 ('738',N'Thống Nhất',N'Thong Nhat',N'Huyện Thống Nhất',N'Thong Nhat District',N'thong nhat',N'75',7),
	 ('739',N'Cẩm Mỹ',N'Cam My',N'Huyện Cẩm Mỹ',N'Cam My District',N'cam my',N'75',7),
	 ('740',N'Long Thành',N'Long Thanh',N'Huyện Long Thành',N'Long Thanh District',N'long thanh',N'75',7),
	 ('741',N'Xuân Lộc',N'Xuan Loc',N'Huyện Xuân Lộc',N'Xuan Loc District',N'xuan loc',N'75',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('742',N'Nhơn Trạch',N'Nhon Trach',N'Huyện Nhơn Trạch',N'Nhon Trach District',N'nhon trach',N'75',7),
	 ('747',N'Vũng Tàu',N'Vung Tau',N'Thành phố Vũng Tàu',N'Vung Tau City',N'vung tau',N'77',4),
	 ('748',N'Bà Rịa',N'Ba Ria',N'Thành phố Bà Rịa',N'Ba Ria City',N'ba ria',N'77',4),
	 ('750',N'Châu Đức',N'Chau Duc',N'Huyện Châu Đức',N'Chau Duc District',N'chau duc',N'77',7),
	 ('751',N'Xuyên Mộc',N'Xuyen Moc',N'Huyện Xuyên Mộc',N'Xuyen Moc District',N'xuyen moc',N'77',7),
	 ('752',N'Long Điền',N'Long Dien',N'Huyện Long Điền',N'Long Dien District',N'long dien',N'77',7),
	 ('753',N'Đất Đỏ',N'Dat Do',N'Huyện Đất Đỏ',N'Dat Do District',N'dat do',N'77',7),
	 ('754',N'Phú Mỹ',N'Phu My',N'Thị xã Phú Mỹ',N'Phu My Town',N'phu my',N'77',6),
	 ('755',N'Côn Đảo',N'Con Dao',N'Huyện Côn Đảo',N'Con Dao District',N'con dao',N'77',7),
	 ('764',N'Gò Vấp',N'Go Vap',N'Quận Gò Vấp',N'Go Vap District',N'go vap',N'79',5);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('765',N'Bình Thạnh',N'Binh Thanh',N'Quận Bình Thạnh',N'Binh Thanh District',N'binh thanh',N'79',5),
	 ('766',N'Tân Bình',N'Tan Binh',N'Quận Tân Bình',N'Tan Binh District',N'tan binh',N'79',5),
	 ('767',N'Tân Phú',N'Tan Phu',N'Quận Tân Phú',N'Tan Phu District',N'tan phu',N'79',5),
	 ('768',N'Phú Nhuận',N'Phu Nhuan',N'Quận Phú Nhuận',N'Phu Nhuan District',N'phu nhuan',N'79',5),
	 ('777',N'Bình Tân',N'Binh Tan',N'Quận Bình Tân',N'Binh Tan District',N'binh tan',N'79',5),
	 ('783',N'Củ Chi',N'Cu Chi',N'Huyện Củ Chi',N'Cu Chi District',N'cu chi',N'79',7),
	 ('784',N'Hóc Môn',N'Hoc Mon',N'Huyện Hóc Môn',N'Hoc Mon District',N'hoc mon',N'79',7),
	 ('785',N'Bình Chánh',N'Binh Chanh',N'Huyện Bình Chánh',N'Binh Chanh District',N'binh chanh',N'79',7),
	 ('786',N'Nhà Bè',N'Nha Be',N'Huyện Nhà Bè',N'Nha Be District',N'nha be',N'79',7),
	 ('787',N'Cần Giờ',N'Can Gio',N'Huyện Cần Giờ',N'Can Gio District',N'can gio',N'79',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('794',N'Tân An',N'Tan An',N'Thành phố Tân An',N'Tan An City',N'tan an',N'80',4),
	 ('795',N'Kiến Tường',N'Kien Tuong',N'Thị xã Kiến Tường',N'Kien Tuong Town',N'kien tuong',N'80',6),
	 ('796',N'Tân Hưng',N'Tan Hung',N'Huyện Tân Hưng',N'Tan Hung District',N'tan hung',N'80',7),
	 ('797',N'Vĩnh Hưng',N'Vinh Hung',N'Huyện Vĩnh Hưng',N'Vinh Hung District',N'vinh hung',N'80',7),
	 ('798',N'Mộc Hóa',N'Moc Hoa',N'Huyện Mộc Hóa',N'Moc Hoa District',N'moc hoa',N'80',7),
	 ('799',N'Tân Thạnh',N'Tan Thanh',N'Huyện Tân Thạnh',N'Tan Thanh District',N'tan thanh',N'80',7),
	 ('800',N'Thạnh Hóa',N'Thanh Hoa',N'Huyện Thạnh Hóa',N'Thanh Hoa District',N'thanh hoa',N'80',7),
	 ('801',N'Đức Huệ',N'Duc Hue',N'Huyện Đức Huệ',N'Duc Hue District',N'duc hue',N'80',7),
	 ('802',N'Đức Hòa',N'Duc Hoa',N'Huyện Đức Hòa',N'Duc Hoa District',N'duc hoa',N'80',7),
	 ('803',N'Bến Lức',N'Ben Luc',N'Huyện Bến Lức',N'Ben Luc District',N'ben luc',N'80',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('804',N'Thủ Thừa',N'Thu Thua',N'Huyện Thủ Thừa',N'Thu Thua District',N'thu thua',N'80',7),
	 ('805',N'Tân Trụ',N'Tan Tru',N'Huyện Tân Trụ',N'Tan Tru District',N'tan tru',N'80',7),
	 ('806',N'Cần Đước',N'Can Duoc',N'Huyện Cần Đước',N'Can Duoc District',N'can duoc',N'80',7),
	 ('807',N'Cần Giuộc',N'Can Giuoc',N'Huyện Cần Giuộc',N'Can Giuoc District',N'can giuoc',N'80',7),
	 ('808',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District',N'chau thanh',N'80',7),
	 ('815',N'Mỹ Tho',N'My Tho',N'Thành phố Mỹ Tho',N'My Tho City',N'my tho',N'82',4),
	 ('816',N'Gò Công',N'Go Cong',N'Thị xã Gò Công',N'Go Cong Town',N'go cong',N'82',6),
	 ('817',N'Cai Lậy',N'Cai Lay',N'Thị xã Cai Lậy',N'Cai Lay Town',N'cai lay',N'82',6),
	 ('818',N'Tân Phước',N'Tan Phuoc',N'Huyện Tân Phước',N'Tan Phuoc District',N'tan phuoc',N'82',7),
	 ('819',N'Cái Bè',N'Cai Be',N'Huyện Cái Bè',N'Cai Be District',N'cai be',N'82',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('820',N'Cai Lậy',N'Cai Lay',N'Huyện Cai Lậy',N'Cai Lay District',N'cai lay',N'82',7),
	 ('821',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District',N'chau thanh',N'82',7),
	 ('822',N'Chợ Gạo',N'Cho Gao',N'Huyện Chợ Gạo',N'Cho Gao District',N'cho gao',N'82',7),
	 ('823',N'Gò Công Tây',N'Go Cong Tay',N'Huyện Gò Công Tây',N'Go Cong Tay District',N'go cong tay',N'82',7),
	 ('824',N'Gò Công Đông',N'Go Cong Dong',N'Huyện Gò Công Đông',N'Go Cong Dong District',N'go cong dong',N'82',7),
	 ('825',N'Tân Phú Đông',N'Tan Phu Dong',N'Huyện Tân Phú Đông',N'Tan Phu Dong District',N'tan phu dong',N'82',7),
	 ('829',N'Bến Tre',N'Ben Tre',N'Thành phố Bến Tre',N'Ben Tre City',N'ben tre',N'83',4),
	 ('831',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District',N'chau thanh',N'83',7),
	 ('832',N'Chợ Lách',N'Cho Lach',N'Huyện Chợ Lách',N'Cho Lach District',N'cho lach',N'83',7),
	 ('833',N'Mỏ Cày Nam',N'Mo Cay Nam',N'Huyện Mỏ Cày Nam',N'Mo Cay Nam District',N'mo cay nam',N'83',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('834',N'Giồng Trôm',N'Giong Trom',N'Huyện Giồng Trôm',N'Giong Trom District',N'giong trom',N'83',7),
	 ('835',N'Bình Đại',N'Binh Dai',N'Huyện Bình Đại',N'Binh Dai District',N'binh dai',N'83',7),
	 ('836',N'Ba Tri',N'Ba Tri',N'Huyện Ba Tri',N'Ba Tri District',N'ba tri',N'83',7),
	 ('837',N'Thạnh Phú',N'Thanh Phu',N'Huyện Thạnh Phú',N'Thanh Phu District',N'thanh phu',N'83',7),
	 ('838',N'Mỏ Cày Bắc',N'Mo Cay Bac',N'Huyện Mỏ Cày Bắc',N'Mo Cay Bac District',N'mo cay bac',N'83',7),
	 ('842',N'Trà Vinh',N'Tra Vinh',N'Thành phố Trà Vinh',N'Tra Vinh City',N'tra vinh',N'84',4),
	 ('844',N'Càng Long',N'Cang Long',N'Huyện Càng Long',N'Cang Long District',N'cang long',N'84',7),
	 ('845',N'Cầu Kè',N'Cau Ke',N'Huyện Cầu Kè',N'Cau Ke District',N'cau ke',N'84',7),
	 ('846',N'Tiểu Cần',N'Tieu Can',N'Huyện Tiểu Cần',N'Tieu Can District',N'tieu can',N'84',7),
	 ('847',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District',N'chau thanh',N'84',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('848',N'Cầu Ngang',N'Cau Ngang',N'Huyện Cầu Ngang',N'Cau Ngang District',N'cau ngang',N'84',7),
	 ('849',N'Trà Cú',N'Tra Cu',N'Huyện Trà Cú',N'Tra Cu District',N'tra cu',N'84',7),
	 ('850',N'Duyên Hải',N'Duyen Hai',N'Huyện Duyên Hải',N'Duyen Hai District',N'duyen hai',N'84',7),
	 ('851',N'Duyên Hải',N'Duyen Hai',N'Thị xã Duyên Hải',N'Duyen Hai Town',N'duyen hai',N'84',6),
	 ('855',N'Vĩnh Long',N'Vinh Long',N'Thành phố Vĩnh Long',N'Vinh Long City',N'vinh long',N'86',4),
	 ('857',N'Long Hồ',N'Long Ho',N'Huyện Long Hồ',N'Long Ho District',N'long ho',N'86',7),
	 ('858',N'Mang Thít',N'Mang Thit',N'Huyện Mang Thít',N'Mang Thit District',N'mang thit',N'86',7),
	 ('859',N'Vũng Liêm',N'Vung Liem',N'Huyện Vũng Liêm',N'Vung Liem District',N'vung liem',N'86',7),
	 ('860',N'Tam Bình',N'Tam Binh',N'Huyện Tam Bình',N'Tam Binh District',N'tam binh',N'86',7),
	 ('861',N'Bình Minh',N'Binh Minh',N'Thị xã Bình Minh',N'Binh Minh Town',N'binh minh',N'86',6);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('862',N'Trà Ôn',N'Tra On',N'Huyện Trà Ôn',N'Tra On District',N'tra on',N'86',7),
	 ('863',N'Bình Tân',N'Binh Tan',N'Huyện Bình Tân',N'Binh Tan District',N'binh tan',N'86',7),
	 ('866',N'Cao Lãnh',N'Cao Lanh',N'Thành phố Cao Lãnh',N'Cao Lanh City',N'cao lanh',N'87',4),
	 ('867',N'Sa Đéc',N'Sa Dec',N'Thành phố Sa Đéc',N'Sa Dec City',N'sa dec',N'87',4),
	 ('868',N'Hồng Ngự',N'Hong Ngu',N'Thành phố Hồng Ngự',N'Hong Ngu City',N'hong ngu',N'87',4),
	 ('869',N'Tân Hồng',N'Tan Hong',N'Huyện Tân Hồng',N'Tan Hong District',N'tan hong',N'87',7),
	 ('870',N'Hồng Ngự',N'Hong Ngu',N'Huyện Hồng Ngự',N'Hong Ngu District',N'hong ngu',N'87',7),
	 ('871',N'Tam Nông',N'Tam Nong',N'Huyện Tam Nông',N'Tam Nong District',N'tam nong',N'87',7),
	 ('872',N'Tháp Mười',N'Thap Muoi',N'Huyện Tháp Mười',N'Thap Muoi District',N'thap muoi',N'87',7),
	 ('873',N'Cao Lãnh',N'Cao Lanh',N'Huyện Cao Lãnh',N'Cao Lanh District',N'cao lanh',N'87',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('874',N'Thanh Bình',N'Thanh Binh',N'Huyện Thanh Bình',N'Thanh Binh District',N'thanh binh',N'87',7),
	 ('875',N'Lấp Vò',N'Lap Vo',N'Huyện Lấp Vò',N'Lap Vo District',N'lap vo',N'87',7),
	 ('876',N'Lai Vung',N'Lai Vung',N'Huyện Lai Vung',N'Lai Vung District',N'lai vung',N'87',7),
	 ('877',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District',N'chau thanh',N'87',7),
	 ('883',N'Long Xuyên',N'Long Xuyen',N'Thành phố Long Xuyên',N'Long Xuyen City',N'long xuyen',N'89',4),
	 ('884',N'Châu Đốc',N'Chau Doc',N'Thành phố Châu Đốc',N'Chau Doc City',N'chau doc',N'89',4),
	 ('886',N'An Phú',N'An Phu',N'Huyện An Phú',N'An Phu District',N'an phu',N'89',7),
	 ('887',N'Tân Châu',N'Tan Chau',N'Thị xã Tân Châu',N'Tan Chau Town',N'tan chau',N'89',6),
	 ('888',N'Phú Tân',N'Phu Tan',N'Huyện Phú Tân',N'Phu Tan District',N'phu tan',N'89',7),
	 ('889',N'Châu Phú',N'Chau Phu',N'Huyện Châu Phú',N'Chau Phu District',N'chau phu',N'89',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('890',N'Tịnh Biên',N'Tinh Bien',N'Huyện Tịnh Biên',N'Tinh Bien District',N'tinh bien',N'89',7),
	 ('891',N'Tri Tôn',N'Tri Ton',N'Huyện Tri Tôn',N'Tri Ton District',N'tri ton',N'89',7),
	 ('892',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District',N'chau thanh',N'89',7),
	 ('893',N'Chợ Mới',N'Cho Moi',N'Huyện Chợ Mới',N'Cho Moi District',N'cho moi',N'89',7),
	 ('894',N'Thoại Sơn',N'Thoai Son',N'Huyện Thoại Sơn',N'Thoai Son District',N'thoai son',N'89',7),
	 ('899',N'Rạch Giá',N'Rach Gia',N'Thành phố Rạch Giá',N'Rach Gia City',N'rach gia',N'91',4),
	 ('900',N'Hà Tiên',N'Ha Tien',N'Thành phố Hà Tiên',N'Ha Tien City',N'ha tien',N'91',4),
	 ('902',N'Kiên Lương',N'Kien Luong',N'Huyện Kiên Lương',N'Kien Luong District',N'kien luong',N'91',7),
	 ('903',N'Hòn Đất',N'Hon Dat',N'Huyện Hòn Đất',N'Hon Dat District',N'hon dat',N'91',7),
	 ('904',N'Tân Hiệp',N'Tan Hiep',N'Huyện Tân Hiệp',N'Tan Hiep District',N'tan hiep',N'91',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('905',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District',N'chau thanh',N'91',7),
	 ('906',N'Giồng Riềng',N'Giong Rieng',N'Huyện Giồng Riềng',N'Giong Rieng District',N'giong rieng',N'91',7),
	 ('907',N'Gò Quao',N'Go Quao',N'Huyện Gò Quao',N'Go Quao District',N'go quao',N'91',7),
	 ('908',N'An Biên',N'An Bien',N'Huyện An Biên',N'An Bien District',N'an bien',N'91',7),
	 ('909',N'An Minh',N'An Minh',N'Huyện An Minh',N'An Minh District',N'an minh',N'91',7),
	 ('910',N'Vĩnh Thuận',N'Vinh Thuan',N'Huyện Vĩnh Thuận',N'Vinh Thuan District',N'vinh thuan',N'91',7),
	 ('911',N'Phú Quốc',N'Phu Quoc',N'Thành phố Phú Quốc',N'Phu Quoc City',N'phu quoc',N'91',4),
	 ('912',N'Kiên Hải',N'Kien Hai',N'Huyện Kiên Hải',N'Kien Hai District',N'kien hai',N'91',7),
	 ('913',N'U Minh Thượng',N'U Minh Thuong',N'Huyện U Minh Thượng',N'U Minh Thuong District',N'u minh thuong',N'91',7),
	 ('914',N'Giang Thành',N'Giang Thanh',N'Huyện Giang Thành',N'Giang Thanh District',N'giang thanh',N'91',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('916',N'Ninh Kiều',N'Ninh Kieu',N'Quận Ninh Kiều',N'Ninh Kieu District',N'ninh kieu',N'92',5),
	 ('917',N'Ô Môn',N'O Mon',N'Quận Ô Môn',N'O Mon District',N'o mon',N'92',5),
	 ('918',N'Bình Thuỷ',N'Binh Thuy',N'Quận Bình Thuỷ',N'Binh Thuy District',N'binh thuy',N'92',5),
	 ('919',N'Cái Răng',N'Cai Rang',N'Quận Cái Răng',N'Cai Rang District',N'cai rang',N'92',5),
	 ('923',N'Thốt Nốt',N'Thot Not',N'Quận Thốt Nốt',N'Thot Not District',N'thot not',N'92',5),
	 ('924',N'Vĩnh Thạnh',N'Vinh Thanh',N'Huyện Vĩnh Thạnh',N'Vinh Thanh District',N'vinh thanh',N'92',7),
	 ('925',N'Cờ Đỏ',N'Co Do',N'Huyện Cờ Đỏ',N'Co Do District',N'co do',N'92',7),
	 ('926',N'Phong Điền',N'Phong Dien',N'Huyện Phong Điền',N'Phong Dien District',N'phong dien',N'92',7),
	 ('927',N'Thới Lai',N'Thoi Lai',N'Huyện Thới Lai',N'Thoi Lai District',N'thoi lai',N'92',7),
	 ('930',N'Vị Thanh',N'Vi Thanh',N'Thành phố Vị Thanh',N'Vi Thanh City',N'vi thanh',N'93',4);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('931',N'Ngã Bảy',N'Nga Bay',N'Thành phố Ngã Bảy',N'Nga Bay City',N'nga bay',N'93',4),
	 ('932',N'Châu Thành A',N'Chau Thanh A',N'Huyện Châu Thành A',N'Chau Thanh A District',N'chau thanh a',N'93',7),
	 ('933',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District',N'chau thanh',N'93',7),
	 ('934',N'Phụng Hiệp',N'Phung Hiep',N'Huyện Phụng Hiệp',N'Phung Hiep District',N'phung hiep',N'93',7),
	 ('935',N'Vị Thuỷ',N'Vi Thuy',N'Huyện Vị Thuỷ',N'Vi Thuy District',N'vi thuy',N'93',7),
	 ('936',N'Long Mỹ',N'Long My',N'Huyện Long Mỹ',N'Long My District',N'long my',N'93',7),
	 ('937',N'Long Mỹ',N'Long My',N'Thị xã Long Mỹ',N'Long My Town',N'long my',N'93',6),
	 ('941',N'Sóc Trăng',N'Soc Trang',N'Thành phố Sóc Trăng',N'Soc Trang City',N'soc trang',N'94',4),
	 ('942',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District',N'chau thanh',N'94',7),
	 ('943',N'Kế Sách',N'Ke Sach',N'Huyện Kế Sách',N'Ke Sach District',N'ke sach',N'94',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('944',N'Mỹ Tú',N'My Tu',N'Huyện Mỹ Tú',N'My Tu District',N'my tu',N'94',7),
	 ('945',N'Cù Lao Dung',N'Cu Lao Dung',N'Huyện Cù Lao Dung',N'Cu Lao Dung District',N'cu lao dung',N'94',7),
	 ('946',N'Long Phú',N'Long Phu',N'Huyện Long Phú',N'Long Phu District',N'long phu',N'94',7),
	 ('947',N'Mỹ Xuyên',N'My Xuyen',N'Huyện Mỹ Xuyên',N'My Xuyen District',N'my xuyen',N'94',7),
	 ('948',N'Ngã Năm',N'Nga Nam',N'Thị xã Ngã Năm',N'Nga Nam Town',N'nga nam',N'94',6),
	 ('949',N'Thạnh Trị',N'Thanh Tri',N'Huyện Thạnh Trị',N'Thanh Tri District',N'thanh tri',N'94',7),
	 ('950',N'Vĩnh Châu',N'Vinh Chau',N'Thị xã Vĩnh Châu',N'Vinh Chau Town',N'vinh chau',N'94',6),
	 ('951',N'Trần Đề',N'Tran De',N'Huyện Trần Đề',N'Tran De District',N'tran de',N'94',7),
	 ('954',N'Bạc Liêu',N'Bac Lieu',N'Thành phố Bạc Liêu',N'Bac Lieu City',N'bac lieu',N'95',4),
	 ('956',N'Hồng Dân',N'Hong Dan',N'Huyện Hồng Dân',N'Hong Dan District',N'hong dan',N'95',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('957',N'Phước Long',N'Phuoc Long',N'Huyện Phước Long',N'Phuoc Long District',N'phuoc long',N'95',7),
	 ('958',N'Vĩnh Lợi',N'Vinh Loi',N'Huyện Vĩnh Lợi',N'Vinh Loi District',N'vinh loi',N'95',7),
	 ('959',N'Giá Rai',N'Gia Rai',N'Thị xã Giá Rai',N'Gia Rai Town',N'gia rai',N'95',6),
	 ('960',N'Đông Hải',N'Dong Hai',N'Huyện Đông Hải',N'Dong Hai District',N'dong hai',N'95',7),
	 ('961',N'Hoà Bình',N'Hoa Binh',N'Huyện Hoà Bình',N'Hoa Binh District',N'hoa binh',N'95',7),
	 ('964',N'Cà Mau',N'Ca Mau',N'Thành phố Cà Mau',N'Ca Mau City',N'ca mau',N'96',4),
	 ('966',N'U Minh',N'U Minh',N'Huyện U Minh',N'U Minh District',N'u minh',N'96',7),
	 ('967',N'Thới Bình',N'Thoi Binh',N'Huyện Thới Bình',N'Thoi Binh District',N'thoi binh',N'96',7),
	 ('968',N'Trần Văn Thời',N'Tran Van Thoi',N'Huyện Trần Văn Thời',N'Tran Van Thoi District',N'tran van thoi',N'96',7),
	 ('969',N'Cái Nước',N'Cai Nuoc',N'Huyện Cái Nước',N'Cai Nuoc District',N'cai nuoc',N'96',7);
INSERT INTO DISTRICTS (DISTRICTS_CODE, DISTRICTS_NAME, DISTRICTS_NAME_ENG, DISTRICTS_FULLNAME, DISTRICTS_FULLNAME_ENG, DISTRICTS_CODE_NAME, PROVINCE_CODE, ADMIN_UNIT_ID) VALUES
	 ('970',N'Đầm Dơi',N'Dam Doi',N'Huyện Đầm Dơi',N'Dam Doi District',N'dam doi',N'96',7),
	 ('971',N'Năm Căn',N'Nam Can',N'Huyện Năm Căn',N'Nam Can District',N'nam can',N'96',7),
	 ('972',N'Phú Tân',N'Phu Tan',N'Huyện Phú Tân',N'Phu Tan District',N'phu tan',N'96',7),
	 ('973',N'Ngọc Hiển',N'Ngoc Hien',N'Huyện Ngọc Hiển',N'Ngoc Hien District',N'ngoc hien',N'96',7),
	 ('769',N'Thủ Đức',N'Thu Duc',N'Thành phố Thủ Đức',N'Thu Duc City',N'thu duc',N'79',3);